// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["asar"] = model.Subcommand{
		Name:        []string{"asar"},
		Description: `A simple extensive tar-like archive format with indexing`,
		Options: []model.Option{{
			Name:        []string{"--help", "-h"},
			Description: `Show help for asar`,
		}, {
			Name:        []string{"--V", "--version"},
			Description: `Output the version number`,
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"pack", "p"},
			Description: `Create asar archive`,
			Args: []model.Arg{{
				Name:        "directory",
				Description: `The directory you want to archive`,
			}, {
				Name:        "output",
				Description: `The name of the output file`,
			}},
		}, {
			Name:        []string{"list", "l"},
			Description: `List files of asar archive`,
			Args: []model.Arg{{
				Name:        "archive",
				Description: `The archive file`,
			}},
		}, {
			Name:        []string{"extract-file", "ef"},
			Description: `Extract one file from archive`,
			Args: []model.Arg{{
				Name:        "archive",
				Description: `The archive file`,
			}, {
				Name:        "filename",
				Description: `The name of the file you want to extract`,
			}},
		}, {
			Name:        []string{"extract", "e"},
			Description: `Extract archive`,
			Args: []model.Arg{{
				Name:        "archive",
				Description: `The archive file`,
			}, {
				Name:        "directory",
				Description: `The directory you want to extract to`,
			}},
		}},
	}
}
