package specs

import (
	"github.com/cpendery/clac/autocomplete/generators/azure"
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["az"] = model.Subcommand{
		Name:        []string{"az"},
		Description: `Azure CLI`,
		Subcommands: []model.Subcommand{
			{Name: []string{"account"}, Description: "Manage Azure subscription information."},
			{Name: []string{"acr"}, Description: "Manage private registries with Azure Container Registries."},
			{Name: []string{"ad"}, Description: "Manage Azure Active Directory Graph entities needed for Role Based Access Control."},
			{Name: []string{"advisor"}, Description: "Manage Azure Advisor."},
			{Name: []string{"afd"}, Description: "Manage Azure Front Door Standard/Premium. For classical Azure Front Door, please refer https://docs.microsoft.com/en-us/cli/azure/network/front-door?view=azure-cli-latest."},
			{Name: []string{"aks"}, Description: "Manage Azure Kubernetes Services."},
			{Name: []string{"ams"}, Description: "Manage Azure Media Services resources."},
			{Name: []string{"apim"}, Description: "Manage Azure API Management services."},
			{Name: []string{"appconfig"}, Description: "Manage App Configurations."},
			{Name: []string{"appservice"}, Description: "Manage App Service plans."},
			{Name: []string{"aro"}, Description: "Manage Azure Red Hat OpenShift clusters."},
			{Name: []string{"backup"}, Description: "Manage Azure Backups."},
			{Name: []string{"batch"}, Description: "Manage Azure Batch."},
			{Name: []string{"bicep"}, Description: "Bicep CLI command group."},
			{Name: []string{"billing"}, Description: "Manage Azure Billing."},
			{Name: []string{"bot"}, Description: "Manage Microsoft Azure Bot Service."},
			{Name: []string{"cache"}, Description: "Commands to manage CLI objects cached using the `--defer` argument."},
			{Name: []string{"capacity"}, Description: "Manage capacity resources."},
			{Name: []string{"cdn"}, Description: "Manage Azure Content Delivery Networks (CDNs)."},
			{Name: []string{"cloud"}, Description: "Manage registered Azure clouds."},
			{Name: []string{"cognitiveservices"}, Description: "Manage Azure Cognitive Services accounts."},
			{Name: []string{"config"}, Description: "Manage Azure CLI configuration."},
			{Name: []string{"configure"}, Description: "Manage Azure CLI configuration. This command is interactive."},
			{Name: []string{"connection"}, Description: "Commands to manage Service Connector local connections which allow local environment to connect Azure Resource. If you want to manage connection for compute service, please run 'az webapp/containerapp/spring connection'."},
			{Name: []string{"consumption"}, Description: "Manage consumption of Azure resources."},
			{Name: []string{"container"}, Description: "Manage Azure Container Instances."},
			{Name: []string{"cosmosdb"}, Description: "Manage Azure Cosmos DB database accounts."},
			{Name: []string{"databoxedge"}, Description: "Support data box edge device and management."},
			{Name: []string{"deployment"}, Description: "Manage Azure Resource Manager template deployment at subscription scope."},
			{Name: []string{"deployment-scripts"}, Description: "Manage deployment scripts at subscription or resource group scope."},
			{Name: []string{"deploymentmanager"}, Description: "Create and manage rollouts for your service."},
			{Name: []string{"disk"}, Description: "Manage Azure Managed Disks."},
			{Name: []string{"disk-access"}, Description: "Manage disk access resources."},
			{Name: []string{"disk-encryption-set"}, Description: "Disk Encryption Set resource."},
			{Name: []string{"dla"}, Description: "Manage Data Lake Analytics accounts, jobs, and catalogs."},
			{Name: []string{"dls"}, Description: "Manage Data Lake Store accounts and filesystems."},
			{Name: []string{"dms"}, Description: "Manage Azure Data Migration Service (classic) instances."},
			{Name: []string{"eventgrid"}, Description: "Manage Azure Event Grid topics, domains, domain topics, system topics partner topics, event subscriptions, system topic event subscriptions and partner topic event subscriptions."},
			{Name: []string{"eventhubs"}, Description: "Manage Azure Event Hubs namespaces, eventhubs, consumergroups and geo recovery configurations - Alias."},
			{Name: []string{"extension"}, Description: "Manage and update CLI extensions."},
			{Name: []string{"feature"}, Description: "Manage resource provider features."},
			{Name: []string{"feedback"}, Description: "Send feedback to the Azure CLI Team."},
			{Name: []string{"find"}, Description: "I'm an AI robot, my advice is based on our Azure documentation as well as the usage patterns of Azure CLI and Azure ARM users. Using me improves Azure products and documentation."},
			{Name: []string{"functionapp"}, Description: "Manage function apps. To install the Azure Functions Core tools see https://github.com/Azure/azure-functions-core-tools."},
			{Name: []string{"group"}, Description: "Manage resource groups and template deployments."},
			{Name: []string{"hdinsight"}, Description: "Manage HDInsight resources."},
			{Name: []string{"identity"}, Description: "Managed Identities."},
			{Name: []string{"image"}, Description: "Manage custom virtual machine images."},
			{Name: []string{"interactive"}, Description: "Start interactive mode. Installs the Interactive extension if not installed already."},
			{Name: []string{"iot"}, Description: "Manage Internet of Things (IoT) assets."},
			{Name: []string{"keyvault"}, Description: "Manage KeyVault keys, secrets, and certificates.",
				Subcommands: []model.Subcommand{
					{Name: []string{"backup"}, Description: "Manage full HSM backup."},
					{Name: []string{"certificate"}, Description: "Manage certificates."},
					{Name: []string{"key"}, Description: "Manage keys.", Subcommands: []model.Subcommand{
						{Name: []string{"backup"}, Description: "Request that a backup of the specified key be downloaded to the client."},
						{Name: []string{"create"}, Description: "Create a new key, stores it, then returns key parameters and attributes to the client."},
						{Name: []string{"decrypt"}, Description: "Decrypt a single block of encrypted data."},
						{Name: []string{"delete"}, Description: "Delete a key of any type from storage in Vault or HSM."},
						{Name: []string{"download"}, Description: "Download the public part of a stored key."},
						{Name: []string{"encrypt"}, Description: "Encrypt an arbitrary sequence of bytes using an encryption key that is stored in a Vault or HSM."},
						{Name: []string{"get-policy-template"}, Description: "Return policy template as JSON encoded policy definition."},
						{Name: []string{"import"}, Description: "Import a private key."},
						{Name: []string{"list"}, Description: "List keys in the specified Vault or HSM."},
						{Name: []string{"list-deleted"}, Description: "List the deleted keys in the specified Vault or HSM."},
						{Name: []string{"list-versions"}, Description: "Retrieves a list of individual key versions with the same key name."},
						{Name: []string{"purge"}, Description: "Permanently delete the specified key."},
						{Name: []string{"random"}, Description: "Get the requested number of random bytes from a managed HSM."},
						{Name: []string{"recover"}, Description: "Recover the deleted key to its latest version."},
						{Name: []string{"restore"}, Description: "Restore a backed up key to a Vault or HSM."},
						{Name: []string{"rotate"}, Description: "Rotate the key based on the key policy by generating a new version of the key."},
						{Name: []string{"set-attributes"}, Description: "The update key operation changes specified attributes of a stored key and can be applied to any key type and key version stored in Vault or HSM."},
						{Name: []string{"show"}, Description: "Get a key's attributes and, if it's an asymmetric key, its public material.", Options: []model.Option{
							{Name: []string{"--id"}, Description: "Id of the key. If specified all other 'Id' arguments should be omitted."},
							{Name: []string{"--name", "-n"}, Description: "Name of the key. Required if --id is not specified", Args: []model.Arg{
								{Name: "key name"},
							}},
							{Name: []string{"--vault-name"}, Description: "Name of the Vault.", Args: []model.Arg{
								{Name: "vault name", Generator: azure.ListKeyVaultsGenerator},
							}},
							{Name: []string{"--version", "-v"}, Description: "The key version. If omitted, uses the latest version."},
							{Name: []string{"--hsm-name"}, Description: "Name of the HSM. (--hsm-name and --vault-name are mutually exclusive,  please specify just one of them)"},
							{Name: []string{"--debug"}, Description: "Increase logging verbosity to show all debug logs.", IsPersistent: true},
							{Name: []string{"--help", "-h"}, Description: "Show this help message and exit.", IsPersistent: true},
							{Name: []string{"--only-show-errors"}, Description: "Only show errors, suppressing warnings.", IsPersistent: true},
							{Name: []string{"--output", "-o"}, Description: "Output format.  Allowed values: json, jsonc, none, table, tsv, yaml, yamlc. Default json", IsPersistent: true, Args: []model.Arg{
								{Name: "output format", Description: "Allowed values: json, jsonc, none, table, tsv, yaml, yamlc. Default json", Suggestions: []model.Suggestion{
									{Name: []string{"json"}}, {Name: []string{"jsonc"}}, {Name: []string{"none"}}, {Name: []string{"table"}}, {Name: []string{"tsv"}}, {Name: []string{"yaml"}}, {Name: []string{"yamlc"}},
								}},
							}},
							{Name: []string{"--query"}, Description: "Increase logging verbosity to show all debug logs.", IsPersistent: true, Args: []model.Arg{
								{Name: "JMESPath query string", Description: "JMESPath query string. See http://jmespath.org/ for more information and examples"},
							}},
							{Name: []string{"--subscription"}, Description: "Increase logging verbosity to show all debug logs.", IsPersistent: true, Args: []model.Arg{
								{Name: "Name or ID of subscription"},
							}},
							{Name: []string{"--verbose"}, Description: "Increase logging verbosity to show all debug logs.", IsPersistent: true},
						}},
						{Name: []string{"show-deleted"}, Description: "Get the public part of a deleted key."},
					}},
					{Name: []string{"network-rule"}, Description: "Manage vault network ACLs."},
					{Name: []string{"private-endpoint-connection"}, Description: "Manage vault/HSM private endpoint connections."},
					{Name: []string{"private-link-resource"}, Description: "Manage vault/HSM private link resources."},
					{Name: []string{"restore"}, Description: "Manage full HSM restore."},
					{Name: []string{"role"}, Description: "Manage user roles for access control."},
					{Name: []string{"secret"}, Description: "Manage secrets."},
					{Name: []string{"security-domain"}, Description: "Manage security domain operations."},
					{Name: []string{"storage"}, Description: "Manage storage accounts."},
					{Name: []string{"check-name"}, Description: "Checks that the managed hsm name is valid and is not already in use."},
					{Name: []string{"create"}, Description: "Create a Vault or HSM."},
					{Name: []string{"delete"}, Description: "Delete a Vault or HSM."},
					{Name: []string{"delete-policy"}, Description: "Delete security policy settings for a Key Vault."},
					{Name: []string{"list"}, Description: "List Vaults and/or HSMs."},
					{Name: []string{"list-deleted"}, Description: "Get information about the deleted Vaults or HSMs in a subscription."},
					{Name: []string{"purge"}, Description: "Permanently delete the specified Vault or HSM. Aka Purges the deleted Vault or HSM."},
					{Name: []string{"recover"}, Description: "Recover a Vault or HSM."},
					{Name: []string{"set-policy"}, Description: "Update security policy settings for a Key Vault."},
					{Name: []string{"show"}, Description: "Show details of a Vault or HSM."},
					{Name: []string{"show-deleted"}, Description: "Show details of a deleted Vault or HSM."},
					{Name: []string{"update"}, Description: "Update the properties of a Vault."},
					{Name: []string{"update-hsm"}, Description: "Update the properties of a HSM."},
					{Name: []string{"wait"}, Description: "Place the CLI in a waiting state until a condition of the Vault is met."},
					{Name: []string{"wait-hsm"}, Description: "Place the CLI in a waiting state until a condition of the HSM is met."},
				},
			},
			{Name: []string{"kusto"}, Description: "Manage Azure Kusto resources."},
			{Name: []string{"lab"}, Description: "Manage Azure DevTest Labs."},
			{Name: []string{"lock"}, Description: "Manage Azure locks."},
			{Name: []string{"logicapp"}, Description: "Manage logic apps."},
			{Name: []string{"login"}, Description: "Log in to Azure."},
			{Name: []string{"logout"}, Description: "Log out to remove access to Azure subscriptions."},
			{Name: []string{"managed-cassandra"}, Description: "Azure Managed Cassandra."},
			{Name: []string{"managedapp"}, Description: "Manage template solutions provided and maintained by Independent Software Vendors (ISVs)."},
			{Name: []string{"managedservices"}, Description: "Manage the registration assignments and definitions in Azure."},
			{Name: []string{"maps"}, Description: "Manage Azure Maps."},
			{Name: []string{"mariadb"}, Description: "Manage Azure Database for MariaDB servers."},
			{Name: []string{"monitor"}, Description: "Manage the Azure Monitor Service."},
			{Name: []string{"mysql"}, Description: "Manage Azure Database for MySQL servers."},
			{Name: []string{"netappfiles"}, Description: "Manage Azure NetApp Files (ANF) Resources."},
			{Name: []string{"network"}, Description: "Manage Azure Network resources."},
			{Name: []string{"policy"}, Description: "Manage resource policies."},
			{Name: []string{"postgres"}, Description: "Manage Azure Database for PostgreSQL servers."},
			{Name: []string{"ppg"}, Description: "Manage Proximity Placement Groups."},
			{Name: []string{"private-link"}, Description: "Private-link association CLI command group."},
			{Name: []string{"provider"}, Description: "Manage resource providers."},
			{Name: []string{"redis"}, Description: "Manage dedicated Redis caches for your Azure applications."},
			{Name: []string{"relay"}, Description: "Manage Azure Relay Service namespaces, WCF relays, hybrid connections, and rules."},
			{Name: []string{"resource"}, Description: "Manage Azure resources."},
			{Name: []string{"resourcemanagement"}, Description: "Resourcemanagement CLI command group."},
			{Name: []string{"rest"}, Description: "Invoke a custom request."},
			{Name: []string{"restore-point"}, Description: "Manage restore point with res."},
			{Name: []string{"role"}, Description: "Manage user roles for access control with Azure Active Directory and service principals."},
			{Name: []string{"search"}, Description: "Manage Azure Search services, admin keys and query keys."},
			{Name: []string{"security"}, Description: "Manage your security posture with Microsoft Defender for Cloud."},
			{Name: []string{"servicebus"}, Description: "Manage Azure Service Bus namespaces, queues, topics, subscriptions, rules and geo-disaster recovery configuration alias."},
			{Name: []string{"sf"}, Description: "Manage and administer Azure Service Fabric clusters."},
			{Name: []string{"sig"}, Description: "Manage shared image gallery."},
			{Name: []string{"signalr"}, Description: "Manage Azure SignalR Service."},
			{Name: []string{"snapshot"}, Description: "Manage point-in-time copies of managed disks, native blobs, or other snapshots."},
			{Name: []string{"sql"}, Description: "Manage Azure SQL Databases and Data Warehouses."},
			{Name: []string{"sshkey"}, Description: "Manage ssh public key with vm."},
			{Name: []string{"staticwebapp"}, Description: "Manage static apps."},
			{Name: []string{"storage"}, Description: "Manage Azure Cloud Storage resources."},
			{Name: []string{"survey"}, Description: "Take Azure CLI survey."},
			{Name: []string{"synapse"}, Description: "Manage and operate Synapse Workspace, Spark Pool, SQL Pool."},
			{Name: []string{"tag"}, Description: "Tag Management on a resource."},
			{Name: []string{"term"}, Description: "Manage marketplace agreement with marketplaceordering."},
			{Name: []string{"ts"}, Description: "Manage template specs at subscription or resource group scope."},
			{Name: []string{"upgrade"}, Description: "Upgrade Azure CLI and extensions."},
			{Name: []string{"version"}, Description: "Show the versions of Azure CLI modules and extensions in JSON format by default or format configured by --output."},
			{Name: []string{"vm"}, Description: "Manage Linux or Windows virtual machines."},
			{Name: []string{"vmss"}, Description: "Manage groupings of virtual machines in an Azure Virtual Machine Scale Set (VMSS)."},
			{Name: []string{"webapp"}, Description: "Manage web apps."},
		},
	}
}
