// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["cot"] = model.Subcommand{
		Name:        []string{"cot"},
		Description: `Command-line utility for CotEditor`,
		Args: []model.Arg{{
			Templates: []model.Template{model.TemplateFilepaths},
		}},
		Options: []model.Option{{
			Name:        []string{"-h", "--help"},
			Description: `Show help message and exit`,
		}, {
			Name:        []string{"-v", "--version"},
			Description: `Show program's version number and exit`,
		}, {
			Name:        []string{"-w", "--wait"},
			Description: `Wait for opened file to be closed`,
		}, {
			Name:        []string{"-g", "--background"},
			Description: `Do not bring the application to the foreground`,
		}, {
			Name:        []string{"-n", "--new"},
			Description: `Create a new blank document`,
		}, {
			Name:        []string{"-l", "--line"},
			Description: `Jump to specific line in opened document`,
			Args: []model.Arg{{
				Name: "line",
			}},
		}, {
			Name:        []string{"-c", "--column"},
			Description: `Jump to specific column in opened document`,
			Args: []model.Arg{{
				Name: "column",
			}},
		}},
	}
}
