// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["dirname"] = model.Subcommand{
		Name:        []string{"dirname"},
		Description: `Return directory portion of pathname`,
		Args: []model.Arg{{
			Templates:   []model.Template{model.TemplateFilepaths},
			Name:        "string",
			Description: `String to operate on (typically filenames)`,
			IsVariadic:  true,
		}},
	}
}
