// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["gibo"] = model.Subcommand{
		Name:        []string{"gibo"},
		Description: `Easy access to gitignore boilerplates`,
		Options: []model.Option{{
			Name:        []string{"--help", "-h"},
			Description: `Show help for gibo`,
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"dump"},
			Description: `Dump one or more boilerplates to STDOUT`,
			Args: []model.Arg{{
				Name:        "boilerplate",
				Description: `Name of the boilerplate to dump`,
				Generator:   nil, // TODO: port over generator
				IsVariadic:  true,
			}},
		}, {
			Name:        []string{"search"},
			Description: `Search for boilerplates`,
			Args: []model.Arg{{
				Name:        "search term",
				Description: `Name of the language or framework to search for`,
			}},
		}, {
			Name:        []string{"root"},
			Description: `Show the directory where gibo stores its boilerplates`,
		}, {
			Name:        []string{"help"},
			Description: `Show help information`,
		}, {
			Name:        []string{"list"},
			Description: `Show the list of available boilerplates`,
		}, {
			Name:        []string{"update"},
			Description: `Update the list of available boilerplates`,
		}, {
			Name:        []string{"version"},
			Description: `Show the current version of gibo installed`,
		}},
	}
}
