// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["hb-service"] = model.Subcommand{
		Name:        []string{"hb-service"},
		Description: `The hb-service command is provided by homebridge-config-ui-x`,
		Options: []model.Option{{
			Name:        []string{"--help", "-h"},
			Description: `Display help for command`,
		}, {
			Name:        []string{"--version", "-v"},
			Description: `Output the version number`,
		}, {
			Name:        []string{"--service-name", "-S"},
			Description: `The name of the homebridge service to install or control`,
			Args: []model.Arg{{
				Name: "service name",
			}},
			IsPersistent: true,
		}, {
			Name:        []string{"--port"},
			Description: `The port to set to the Homebridge UI when installing as a service`,
			Args: []model.Arg{{
				Name: "port",
			}},
			IsPersistent: true,
		}, {
			Name:        []string{"--user"},
			Description: `The user account the Homebridge service will be installed as (Linux, macOS only)`,
			Args: []model.Arg{{
				Name: "user",
			}},
			IsPersistent: true,
		}, {
			Name: []string{"--plugin-path", "-P"},
			Args: []model.Arg{{
				Name: "path",
			}},
			IsPersistent: true,
		}, {
			Name: []string{"--user-storage-path", "-U"},
			Args: []model.Arg{{
				Name: "path",
			}},
			IsPersistent: true,
		}, {
			Name:         []string{"--no-timestamp", "-T"},
			IsPersistent: true,
		}, {
			Name: []string{"--gid"},
			Args: []model.Arg{{
				Name: "number",
			}},
			IsPersistent: true,
		}, {
			Name: []string{"--uid"},
			Args: []model.Arg{{
				Name: "number",
			}},
			IsPersistent: true,
		}, {
			Name:         []string{"--docker"},
			IsPersistent: true,
		}, {
			Name:         []string{"--allow-root"},
			IsPersistent: true,
		}, {
			Name:         []string{"--stdout"},
			IsPersistent: true,
		}, {
			Name:         []string{"--strict-plugin-resolution"},
			IsPersistent: true,
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"install"},
			Description: `Install homebridge as a service`,
		}, {
			Name:        []string{"uninstall"},
			Description: `Remove the homebridge service`,
		}, {
			Name:        []string{"start"},
			Description: `Start the homebridge service`,
		}, {
			Name:        []string{"stop"},
			Description: `Stop the homebridge service`,
		}, {
			Name:        []string{"restart"},
			Description: `Restart the homebridge service`,
		}, {
			Name:        []string{"rebuild"},
			Description: `Rebuild UI`,
			Options: []model.Option{{
				Name:        []string{"--all"},
				Description: `Rebuild all npm modules (use after updating Node.js)`,
			}},
		}, {
			Name:        []string{"run"},
			Description: `Run homebridge daemon`,
		}, {
			Name:        []string{"logs"},
			Description: `Tails the homebridge service logs`,
		}, {
			Name:        []string{"update-node"},
			Description: `Update Node.js`,
			Args: []model.Arg{{
				Name:       "version",
				IsOptional: true,
			}},
		}},
	}
}
