// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["klist"] = model.Subcommand{
		Name:        []string{"klist"},
		Description: `Reads and displays the current tickets in the credential cache (also known as the ticket file)`,
		Options: []model.Option{{
			Name:        []string{"-c"},
			Description: `Credential cache to list`,
			Args: []model.Arg{{
				Name: "cache",
			}},
		}, {
			Name:        []string{"--cache"},
			Description: `Credential cache to list`,
			Args: []model.Arg{{
				Name: "cache",
			}},
		}, {
			Name:        []string{"-s", "-t", "--test"},
			Description: `Test for there being an active and valid TGT for the local realm of the user in the credential cache`,
		}, {
			Name:        []string{"-T", "--tokens"},
			Description: `Display AFS tokens`,
		}, {
			Name:        []string{"-5", "--v5"},
			Description: `Display v5 cred cache (this is the default)`,
		}, {
			Name:        []string{"-f"},
			Description: `Include ticket flags in short form, each character stands for a specific flag`,
		}, {
			Name:        []string{"-v", "--verbose"},
			Description: `Verbose output. Include all possible information`,
		}, {
			Name:        []string{"-l", "--list-all"},
			Description: `List the credential caches for the current users, not all cache types supports listing multiple caches`,
		}, {
			Name:        []string{"--json"},
			Description: `JSON formatted output`,
		}, {
			Name:        []string{"--hidden"},
			Description: `Verbose output`,
		}},
	}
}
