// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["lima"] = model.Subcommand{
		Name:        []string{"lima"},
		Description: `Lima is an alias for "limactl shell $LIMA_INSTANCE"`,
		Args: []model.Arg{{
			Name:       "COMMAND",
			IsOptional: true,
			IsCommand:  true,
			IsVariadic: true,
		}},
		Options: []model.Option{{
			Name:        []string{"-h", "--help"},
			Description: `Help for lima`,
		}},
	}
}
