// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["neofetch"] = model.Subcommand{
		Name:        []string{"neofetch"},
		Description: `The most complete system information CLI tool`,
		Args: []model.Arg{{
			Name:        "Information lines",
			Suggestions: []model.Suggestion{{Name: []string{`os`}}, {Name: []string{`host`}}, {Name: []string{`kernel`}}, {Name: []string{`uptime`}}, {Name: []string{`packages`}}, {Name: []string{`shell`}}, {Name: []string{`term`}}, {Name: []string{`cpu`}}, {Name: []string{`gpu`}}, {Name: []string{`memory`}}, {Name: []string{`disk`}}, {Name: []string{`battery`}}, {Name: []string{`resolution`}}, {Name: []string{`wm`}}, {Name: []string{`de`}}, {Name: []string{`theme`}}, {Name: []string{`wm_theme`}}, {Name: []string{`icons`}}},
			IsVariadic:  true,
		}},
		Options: []model.Option{{
			Name:        []string{"--help", "-h"},
			Description: `Show help for neofetch`,
		}, {
			Name:        []string{"--disable"},
			Description: `Disable information line`,
			Args: []model.Arg{{
				Name:        "Information lines",
				Suggestions: []model.Suggestion{{Name: []string{`os`}}, {Name: []string{`host`}}, {Name: []string{`kernel`}}, {Name: []string{`uptime`}}, {Name: []string{`packages`}}, {Name: []string{`shell`}}, {Name: []string{`term`}}, {Name: []string{`cpu`}}, {Name: []string{`gpu`}}, {Name: []string{`memory`}}, {Name: []string{`disk`}}, {Name: []string{`battery`}}, {Name: []string{`resolution`}}, {Name: []string{`wm`}}, {Name: []string{`de`}}, {Name: []string{`theme`}}, {Name: []string{`wm_theme`}}, {Name: []string{`icons`}}},
			}},
		}, {
			Name:        []string{"--title_fqdn"},
			Description: `Hide/Show Fully Qualified Domain Name in title`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--package_managers"},
			Description: `Hide/Show Package Manager names`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}, {Name: []string{`tiny`}}},
			}},
		}, {
			Name:        []string{"--os_arch"},
			Description: `Hide/Show OS architecture`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--speed_type"},
			Description: `Change the type of cpu speed to display`,
			Args: []model.Arg{{
				Name:        "type",
				Suggestions: []model.Suggestion{{Name: []string{`current`}}, {Name: []string{`min`}}, {Name: []string{`bios`}}, {Name: []string{`scaling_current`}}, {Name: []string{`scaling_min`}}, {Name: []string{`scaling_max`}}},
			}},
		}, {
			Name:        []string{"--speed_shorthand"},
			Description: `Whether or not to show decimals in CPU speed`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--cpu_brand"},
			Description: `Enable/Disable CPU brand in output`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--cpu_cores"},
			Description: `Whether or not to display the number of CPU cores`,
			Args: []model.Arg{{
				Name:        "type",
				Suggestions: []model.Suggestion{{Name: []string{`logical`}}, {Name: []string{`physical`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--cpu_speed"},
			Description: `Hide/Show cpu speed`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--cpu_temp"},
			Description: `Hide/Show cpu temperature`,
			Args: []model.Arg{{
				Name:        "unit/off",
				Suggestions: []model.Suggestion{{Name: []string{`C`}}, {Name: []string{`F`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--distro_shorthand"},
			Description: `Shorten the output of distro`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}, {Name: []string{`tiny`}}},
			}},
		}, {
			Name:        []string{"--kernel_shorthand"},
			Description: `Shorten the output of kernel`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--uptime_shorthand"},
			Description: `Shorten the output of uptime`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}, {Name: []string{`tiny`}}},
			}},
		}, {
			Name:        []string{"--refresh_rate"},
			Description: `Whether to display the refresh rate of each monitor`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--gpu_brand"},
			Description: `Enable/Disable GPU brand in output`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--gpu_type"},
			Description: `Which GPU to display`,
			Args: []model.Arg{{
				Name:        "type",
				Suggestions: []model.Suggestion{{Name: []string{`all`}}, {Name: []string{`dedicated`}}, {Name: []string{`integrated`}}},
			}},
		}, {
			Name:        []string{"--de_version"},
			Description: `Show/Hide Desktop Environment version`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--gtk_shorthand"},
			Description: `Shorten output of gtk theme/icons`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--gtk2"},
			Description: `Enable/Disable gtk2 theme/font/icons output`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--gtk3"},
			Description: `Enable/Disable gtk3 theme/font/icons output`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--shell_path"},
			Description: `Enable/Disable showing $SHELL path`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--shell_version"},
			Description: `Enable/Disable showing $SHELL version`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--disk_show"},
			Description: `Which disks to display`,
			Args: []model.Arg{{
				Name:        "disk",
				Suggestions: []model.Suggestion{{Name: []string{`/dev/sd`}}, {Name: []string{`/dev/nvme`}}, {Name: []string{`/dev/mmcblk`}}, {Name: []string{`/dev/mapper`}}, {Name: []string{`/mnt`}}, {Name: []string{`/run/media`}}},
			}},
		}, {
			Name:        []string{"--disk_subtitle"},
			Description: `What information to append to the Disk subtitle`,
			Args: []model.Arg{{
				Name:        "type",
				Suggestions: []model.Suggestion{{Name: []string{`name`}}, {Name: []string{`mount`}}, {Name: []string{`dir`}}, {Name: []string{`none`}}},
			}},
		}, {
			Name:        []string{"--disk_percent"},
			Description: `Hide/Show disk percent`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--ip_host"},
			Description: `URL to query for public IP`,
			Args: []model.Arg{{
				Name: "https://...",
			}},
		}, {
			Name:        []string{"--ip_timeout"},
			Description: `Public IP timeout`,
			Args: []model.Arg{{
				Name: "X seconds",
			}},
		}, {
			Name:        []string{"--memory_percent"},
			Description: `Display memory percentage`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--memory_unit"},
			Description: `Memory output unit`,
			Args: []model.Arg{{
				Name:        "unit",
				Suggestions: []model.Suggestion{{Name: []string{`kib`}}, {Name: []string{`mib`}}, {Name: []string{`gib`}}},
			}},
		}, {
			Name:        []string{"--colors"},
			Description: `Changes the text colors`,
			Args: []model.Arg{{
				Name: "Title",
			}, {
				Name: "@",
			}, {
				Name: "Underline",
			}, {
				Name: "Subtitle",
			}, {
				Name: "Colon",
			}, {
				Name: "Info",
			}},
		}, {
			Name:        []string{"--underline"},
			Description: `Enable/Disable the underline`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--underline_char"},
			Description: `Character to use when underlining title`,
			Args: []model.Arg{{
				Name: "char",
			}},
		}, {
			Name:        []string{"--bold"},
			Description: `Enable/Disable bold text`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--separator"},
			Description: `Changes the default ':' separator to the specified string`,
			Args: []model.Arg{{
				Name: "string",
			}},
		}, {
			Name:        []string{"--color_blocks"},
			Description: `Enable/Disable the color blocks`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--col_offset"},
			Description: `Left-padding of color blocks`,
			Args: []model.Arg{{
				Name:        "number",
				Suggestions: []model.Suggestion{{Name: []string{`auto`}}, {Name: []string{`[0-9]+`}}},
			}},
		}, {
			Name:        []string{"--block_width"},
			Description: `Width of color blocks in spaces`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--block_height"},
			Description: `Height of color blocks in lines`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--block_range"},
			Description: `Range of colors to print as blocks`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}, {
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--bar_char"},
			Description: `Characters to use when drawing bars`,
			Args: []model.Arg{{
				Name: "Elapsed char",
			}, {
				Name: "Total char",
			}},
		}, {
			Name:        []string{"--bar_border"},
			Description: `Whether or not to surround the bar with '[]'`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--bar_length"},
			Description: `Length in spaces to make the bars`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--bar_colors"},
			Description: `Colors to make the bar`,
			Args: []model.Arg{{
				Name: "Elapsed",
			}, {
				Name: "Total",
			}},
		}, {
			Name:        []string{"--cpu_display"},
			Description: `CPU bar mode`,
			Args: []model.Arg{{
				Name:        "mode",
				Suggestions: []model.Suggestion{{Name: []string{`bar`}}, {Name: []string{`infobar`}}, {Name: []string{`barinfo`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--memory_display"},
			Description: `Memory display mode`,
			Args: []model.Arg{{
				Name:        "mode",
				Suggestions: []model.Suggestion{{Name: []string{`bar`}}, {Name: []string{`infobar`}}, {Name: []string{`barinfo`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--battery_display"},
			Description: `Battery display mode`,
			Args: []model.Arg{{
				Name:        "mode",
				Suggestions: []model.Suggestion{{Name: []string{`bar`}}, {Name: []string{`infobar`}}, {Name: []string{`barinfo`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--disk_display"},
			Description: `Disk display mode`,
			Args: []model.Arg{{
				Name:        "mode",
				Suggestions: []model.Suggestion{{Name: []string{`bar`}}, {Name: []string{`infobar`}}, {Name: []string{`barinfo`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"--backend"},
			Description: `Which image backend to use`,
			Args: []model.Arg{{
				Name:        "backend",
				Suggestions: []model.Suggestion{{Name: []string{`ascii`}}, {Name: []string{`caca`}}, {Name: []string{`chafa`}}, {Name: []string{`jp2a`}}, {Name: []string{`iterm2`}}, {Name: []string{`off`}}, {Name: []string{`pixterm`}}, {Name: []string{`pot`}}, {Name: []string{`sixel`}}, {Name: []string{`termpix`}}, {Name: []string{`tycat`}}, {Name: []string{`w3m`}}, {Name: []string{`kitty`}}},
			}},
		}, {
			Name:        []string{"--source"},
			Description: `Which image or ascii file to use`,
			Args: []model.Arg{{
				Templates:   []model.Template{model.TemplateFilepaths},
				Name:        "source",
				Suggestions: []model.Suggestion{{Name: []string{`auto`}}, {Name: []string{`ascii`}}, {Name: []string{`wallpaper`}}},
			}},
		}, {
			Name:        []string{"--ascii"},
			Description: `Same as --backend ascii`,
		}, {
			Name:        []string{"--caca"},
			Description: `Same as --backend caca`,
		}, {
			Name:        []string{"--chafa"},
			Description: `Same as --backend chafa`,
		}, {
			Name:        []string{"--iterm2"},
			Description: `Same as --backend iterm2`,
		}, {
			Name:        []string{"--jp2a"},
			Description: `Same as --backend jp2a`,
		}, {
			Name:        []string{"--kitty"},
			Description: `Same as --backend kitty`,
		}, {
			Name:        []string{"--pot"},
			Description: `Same as --backend pot`,
		}, {
			Name:        []string{"--pixterm"},
			Description: `Same as --backend pixterm`,
		}, {
			Name:        []string{"--sixel"},
			Description: `Same as --backend sixel`,
		}, {
			Name:        []string{"--termpix"},
			Description: `Same as --backend termpix`,
		}, {
			Name:        []string{"--tycat"},
			Description: `Same as --backend tycat`,
		}, {
			Name:        []string{"--w3m"},
			Description: `Same as --backend w3m`,
		}, {
			Name:        []string{"--off"},
			Description: `Same as --backend off`,
		}, {
			Name:        []string{"--ascii_colors"},
			Description: `Colors to print the ascii art`,
			Args: []model.Arg{{
				Name: "Color 1",
			}, {
				Name: "Color 2",
			}, {
				Name: "Color 3",
			}, {
				Name: "Color 4",
			}, {
				Name: "Color 5",
			}, {
				Name: "Color 6",
			}},
		}, {
			Name:        []string{"--ascii_distro"},
			Description: `Which Distro's ascii art to print`,
			Args: []model.Arg{{
				Name: "OS",
			}},
		}, {
			Name:        []string{"--ascii_bold"},
			Description: `Whether or not to bold the ascii logo`,
			Args: []model.Arg{{
				Name:        "on/off",
				Suggestions: []model.Suggestion{{Name: []string{`on`}}, {Name: []string{`off`}}},
			}},
		}, {
			Name:        []string{"-L", "--logo"},
			Description: `Hide the info text and only show the ascii logo`,
		}, {
			Name:        []string{"--loop"},
			Description: `Redraw the image constantly until Ctrl+C is used`,
		}, {
			Name:        []string{"--size"},
			Description: `How to size the image`,
			Args: []model.Arg{{
				Name:        "size",
				Suggestions: []model.Suggestion{{Name: []string{`auto`}}, {Name: []string{`[0-9]+px`}}, {Name: []string{`[0-9]+%`}}},
			}},
		}, {
			Name:        []string{"--crop_mode"},
			Description: `Which crop mode to use`,
			Args: []model.Arg{{
				Name:        "mode",
				Suggestions: []model.Suggestion{{Name: []string{`normal`}}, {Name: []string{`fit`}}, {Name: []string{`fill`}}},
			}},
		}, {
			Name:        []string{"--crop_offset"},
			Description: `Change the crop offset for normal mode`,
			Args: []model.Arg{{
				Name:        "offset",
				Suggestions: []model.Suggestion{{Name: []string{`northwest`}}, {Name: []string{`north`}}, {Name: []string{`northeast`}}},
			}},
		}, {
			Name:        []string{"--xoffset"},
			Description: `How close the image will be to the left edge of the window. This only works with w3m`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--yoffset"},
			Description: `How close the image will be to the top edge of the window. This only works with w3m`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--gap"},
			Description: `Gap between image and text`,
			Args: []model.Arg{{
				Name: "[0-9]+",
			}},
		}, {
			Name:        []string{"--clean"},
			Description: `Delete cached files and thumbnails`,
		}, {
			Name:        []string{"--config"},
			Description: `Specify a path to a custom config file`,
			Args: []model.Arg{{
				Templates:   []model.Template{model.TemplateFilepaths},
				Name:        "file/none",
				Suggestions: []model.Suggestion{{Name: []string{`none`}}},
			}},
		}, {
			Name:        []string{"--no_config"},
			Description: `Don't create the user config file`,
		}, {
			Name:        []string{"--print_config"},
			Description: `Print the default config file to stdout`,
		}, {
			Name:        []string{"--stdout"},
			Description: `Turn off all colors and disables any ASCII/image backend`,
		}, {
			Name:        []string{"--version"},
			Description: `Show neofetch version`,
		}, {
			Name:        []string{"-v"},
			Description: `Display error messages`,
		}, {
			Name:        []string{"-vv"},
			Description: `Display a verbose log for error reporting`,
		}, {
			Name:        []string{"--gen-man"},
			Description: `Generate a manpage for neofetch in your PWD`,
		}},
	}
}
