// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["psql"] = model.Subcommand{
		Name:        []string{"psql"},
		Description: `Psql is a terminal-based front-end to PostgreSQL`,
		Args:        []model.Arg{{}},
		Options: []model.Option{{
			Name:        []string{"-a", "--echo-all"},
			Description: `Print all nonempty input lines to standard output as they are read. (This does not apply to lines read interactively.) This is equivalent to setting the variable ECHO to all`,
		}, {
			Name:        []string{"-A", "--no-align"},
			Description: `Switches to unaligned output mode. (The default output mode is aligned.) This is equivalent to pset format unaligned`,
		}, {
			Name:        []string{"-b", "--echo-errors"},
			Description: `Print failed SQL commands to standard error output. This is equivalent to setting the variable ECHO to errors`,
		}, {
			Name:        []string{"-c", "--command"},
			Description: `Specifies that psql is to execute the given command string, command. This option can be repeated and combined in any order with the -f option. When either -c or -f is specified, psql does not read commands from standard input; instead it terminates after processing all the -c and -f options in sequence`,
			Args: []model.Arg{{
				Name:        "command",
				Description: `A command string that is completely parsable by the server (i.e., it contains no psql-specific features), or a single backslash command. Thus you cannot mix SQL and psql meta-commands within a -c option. To achieve that, you could use repeated -c options or pipe the string into psql`,
			}},
		}, {
			Name:        []string{"--csv"},
			Description: `Switches to CSV (Comma-Separated Values) output mode. This is equivalent to \pset format csv`,
		}, {
			Name:        []string{"-d", "--dbname"},
			Description: `Specifies the name of the database to connect to. This is equivalent to specifying dbname as the first non-option argument on the command line. The dbname can be a connection string. If so, connection string parameters will override any conflicting command line options`,
			Args: []model.Arg{{
				Name: "dbname",
			}},
		}, {
			Name:        []string{"-e", "--echo-queries"},
			Description: `Copy all SQL commands sent to the server to standard output as well. This is equivalent to setting the variable ECHO to queries`,
		}, {
			Name:        []string{"-E", "--echo-hidden"},
			Description: `Echo the actual queries generated by d and other backslash commands. You can use this to study psql's internal operations. This is equivalent to setting the variable ECHO_HIDDEN to on`,
		}, {
			Name:        []string{"-f", "--file"},
			Description: `Read commands from the file filename, rather than standard input. This option can be repeated and combined in any order with the -c option. When either -c or -f is specified, psql does not read commands from standard input; instead it terminates after processing all the -c and -f options in sequence. Except for that, this option is largely equivalent to the meta-command i. If filename is - (hyphen), then standard input is read until an EOF indication or q meta-command. This can be used to intersperse interactive input with input from files. Note however that Readline is not used in this case (much as if -n had been specified). Using this option is subtly different from writing psql < filename. In general, both will do what you expect, but using -f enables some nice features such as error messages with line numbers. There is also a slight chance that using this option will reduce the start-up overhead. On the other hand, the variant using the shell's input redirection is (in theory) guaranteed to yield exactly the same output you would have received had you entered everything by hand`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "filename",
			}},
		}, {
			Name:        []string{"-F", "--field-separator"},
			Description: `Use separator as the field separator for unaligned output. This is equivalent to \pset fieldsep or \\f`,
			Args: []model.Arg{{
				Name: "separator",
			}},
		}, {
			Name:        []string{"-h", "--host"},
			Description: `Specifies the host name of the machine on which the server is running. If the value begins with a slash, it is used as the directory for the Unix-domain socket`,
			Args: []model.Arg{{
				Name: "hostname",
			}},
		}, {
			Name:        []string{"-H", "--html"},
			Description: `Switches to HTML output mode. This is equivalent to \pset format html or the \H command`,
		}, {
			Name:        []string{"-l", "--list"},
			Description: `List all available databases, then exit. Other non-connection options are ignored. This is similar to the meta-command list. When this option is used, psql will connect to the database postgres, unless a different database is named on the command line (option -d or non-option argument, possibly via a service entry, but not via an environment variable)`,
		}, {
			Name:        []string{"-L", "--log-file"},
			Description: `Write all query output into file filename, in addition to the normal output destination`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "filename",
			}},
		}, {
			Name:        []string{"-n", "--no-readline"},
			Description: `Do not use Readline for line editing and do not use the command history. This can be useful to turn off tab expansion when cutting and pasting`,
		}, {
			Name:        []string{"-o", "--output"},
			Description: `Put all query output into file filename. This is equivalent to the command \o`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "filename",
			}},
		}, {
			Name:        []string{"-p", "--port"},
			Description: `Specifies the TCP port or the local Unix-domain socket file extension on which the server is listening for connections. Defaults to the value of the PGPORT environment variable or, if not set, to the port specified at compile time, usually 5432`,
			Args: []model.Arg{{
				Name: "port",
			}},
		}, {
			Name:        []string{"-P", "--pset"},
			Description: `Specifies printing options, in the style of \pset. Note that here you have to separate name and value with an equal sign instead of a space. For example, to set the output format to LaTeX, you could write -P format=latex`,
			Args: []model.Arg{{
				Name: "assignment",
			}},
		}, {
			Name:        []string{"-q", "--quiet"},
			Description: `Specifies that psql should do its work quietly. By default, it prints welcome messages and various informational output. If this option is used, none of this happens. This is useful with the -c option. This is equivalent to setting the variable QUIET to on`,
		}, {
			Name:        []string{"-R", "--record-separator"},
			Description: `Use separator as the record separator for unaligned output. This is equivalent to \pset recordsep`,
			Args: []model.Arg{{
				Name: "separator",
			}},
		}, {
			Name:        []string{"-s", "--single-step"},
			Description: `Run in single-step mode. That means the user is prompted before each command is sent to the server, with the option to cancel execution as well. Use this to debug scripts`,
		}, {
			Name:        []string{"-S", "--single-line"},
			Description: `Runs in single-line mode where a newline terminates an SQL command, as a semicolon does`,
		}, {
			Name:        []string{"-t", "--tuples-only"},
			Description: `Turn off printing of column names and result row count footers, etc. This is equivalent to 	 or pset tuples_only`,
		}, {
			Name:        []string{"-T", "--table-attr"},
			Description: `Specifies options to be placed within the HTML table tag. See \pset tableattr for details`,
			Args: []model.Arg{{
				Name: "table_options",
			}},
		}, {
			Name:        []string{"-U", "--username"},
			Description: `Turn off printing of column names and result row count footers, etc. This is equivalent to 	 or pset tuples_only`,
			Args: []model.Arg{{
				Name: "username",
			}},
		}, {
			Name:        []string{"-v", "--set", "--variable"},
			Description: `Perform a variable assignment, like the set meta-command. Note that you must separate name and value, if any, by an equal sign on the command line. To unset a variable, leave off the equal sign. To set a variable with an empty value, use the equal sign but leave off the value. These assignments are done during command line processing, so variables that reflect connection state will get overwritten later`,
			Args: []model.Arg{{
				Name: "username",
			}},
		}, {
			Name:        []string{"-V", "--version"},
			Description: `Print the psql version and exit`,
		}, {
			Name:        []string{"-w", "--no-password"},
			Description: `Never issue a password prompt. If the server requires password authentication and a password is not available from other sources such as a .pgpass file, the connection attempt will fail. This option can be useful in batch jobs and scripts where no user is present to enter a password. Note that this option will remain set for the entire session, and so it affects uses of the meta-command connect as well as the initial connection attempt`,
		}, {
			Name:        []string{"-W", "--password"},
			Description: `Force psql to prompt for a password before connecting to a database, even if the password will not be used. If the server requires password authentication and a password is not available from other sources such as a .pgpass file, psql will prompt for a password in any case. However, psql will waste a connection attempt finding out that the server wants a password. In some cases it is worth typing -W to avoid the extra connection attempt. Note that this option will remain set for the entire session, and so it affects uses of the meta-command connect as well as the initial connection attempt`,
		}, {
			Name:        []string{"-x", "--expanded"},
			Description: `Turn on the expanded table formatting mode. This is equivalent to \x or \pset expanded`,
		}, {
			Name:        []string{"-X", "--no-psqlrc"},
			Description: `Do not read the start-up file (neither the system-wide psqlrc file nor the user's ~/.psqlrc file)`,
		}, {
			Name:        []string{"-z", "--field-separator-zero"},
			Description: `Set the field separator for unaligned output to a zero byte. This is equivalent to pset fieldsep_zero`,
		}, {
			Name:        []string{"-0", "--record-separator-zero"},
			Description: `Set the record separator for unaligned output to a zero byte. This is useful for interfacing, for example, with xargs -0. This is equivalent to pset recordsep_zero`,
		}, {
			Name:        []string{"-1", "--single-transaction"},
			Description: `This option can only be used in combination with one or more -c and/or -f options. It causes psql to issue a BEGIN command before the first such option and a COMMIT command after the last one, thereby wrapping all the commands into a single transaction. This ensures that either all the commands complete successfully, or no changes are applied. If the commands themselves contain BEGIN, COMMIT, or ROLLBACK, this option will not have the desired effects. Also, if an individual command cannot be executed inside a transaction block, specifying this option will cause the whole transaction to fail`,
		}, {
			Name:        []string{"-?", "--help"},
			Description: `Show help about psql and exit`,
		}},
	}
}
