// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["publish"] = model.Subcommand{
		Name:        []string{"publish"},
		Description: ``,
		Options: []model.Option{{
			Name:        []string{"--help", "-h"},
			Description: `Show help for publish`,
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"new"},
			Description: `Set up a new website in the current folder`,
		}, {
			Name:        []string{"run"},
			Description: `Generate and run a localhost server on default port 8000 for the website in the current folder`,
			Options: []model.Option{{
				Name:        []string{"-p", "--port"},
				Description: `Customize the port`,
				Args: []model.Arg{{
					Name: "port",
				}},
			}},
		}, {
			Name:        []string{"deploy"},
			Description: `Generate and deploy the website in the current folder`,
		}, {
			Name:        []string{"generate"},
			Description: `Generate the website in the current folder`,
		}},
	}
}
