// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["readlink"] = model.Subcommand{
		Name:        []string{"readlink"},
		Description: `Display file status`,
		Args: []model.Arg{{
			Templates:   []model.Template{model.TemplateFilepaths},
			Name:        "file",
			Description: `File(s) to readlink`,
			IsVariadic:  true,
		}},
		Options: []model.Option{{
			Name:        []string{"-f"},
			Description: `Display information using the specified format; similar to printf(3) formats in that they start with %, are then followed by a sequence of formatting characters, and end in a character that selects the field of the struct stat which is to be formatted`,
			Args: []model.Arg{{
				Name: "format",
			}},
		}, {
			Name:        []string{"-n"},
			Description: `Do not force a newline to appear at the end of each piece of output`,
		}},
	}
}
