// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["rsync"] = model.Subcommand{
		Name:        []string{"rsync"},
		Description: `Rsync is a file transfer program capable of efficient remote update via a fast differencing algorithm`,
		Args: []model.Arg{{
			Name:       "SRC",
			Generator:  nil, // TODO: port over generator
			IsVariadic: true,
		}, {
			Name:      "DEST",
			Generator: nil, // TODO: port over generator
		}},
		Options: []model.Option{{
			Name:        []string{"-v", "--verbose"},
			Description: `Increase verbosity`,
		}, {
			Name:        []string{"--info"},
			Description: `Fine-grained informational verbosity`,
			Args: []model.Arg{{
				Name:        "BACKUP",
				Description: `Mention files backed up`,
			}, {
				Name:        "COPY",
				Description: `Mention files copied locally on the receiving side`,
			}, {
				Name:        "DEL",
				Description: `Mention deletions on the receiving side`,
			}, {
				Name:        "FLIST",
				Description: `Mention file-list receiving/sending (levels 1-2)`,
			}, {
				Name:        "MISC",
				Description: `Mention miscellaneous information (levels 1-2)`,
			}, {
				Name:        "MOUNT",
				Description: `Mention mounts that were found or skipped`,
			}, {
				Name:        "NAME",
				Description: `Mention 1) updated file/dir names, 2) unchanged names`,
			}, {
				Name:        "PROGRESS",
				Description: `Mention 1) per-file progress or 2) total transfer progress`,
			}, {
				Name:        "REMOVE",
				Description: `Mention files removed on the sending side`,
			}, {
				Name:        "SKIP",
				Description: `Mention files that are skipped due to options used`,
			}, {
				Name:        "STATS",
				Description: `Mention statistics at end of run (levels 1-3)`,
			}, {
				Name:        "SYMSAFE",
				Description: `Mention symlinks that are unsafe`,
			}, {
				Name:        "ALL",
				Description: `Set all --info options (e.g. all4)`,
			}, {
				Name:        "NONE",
				Description: `Silence all --info options (same as all0)`,
			}, {
				Name:        "HELP",
				Description: `Output this help message`,
			}},
		}, {
			Name:        []string{"--debug"},
			Description: `Fine-grained debug verbosity`,
			Args: []model.Arg{{
				Name:        "BACKUP",
				Description: `Mention files backed up`,
			}, {
				Name:        "COPY",
				Description: `Mention files copied locally on the receiving side`,
			}, {
				Name:        "DEL",
				Description: `Mention deletions on the receiving side`,
			}, {
				Name:        "FLIST",
				Description: `Mention file-list receiving/sending (levels 1-2)`,
			}, {
				Name:        "MISC",
				Description: `Mention miscellaneous information (levels 1-2)`,
			}, {
				Name:        "MOUNT",
				Description: `Mention mounts that were found or skipped`,
			}, {
				Name:        "NAME",
				Description: `Mention 1) updated file/dir names, 2) unchanged names`,
			}, {
				Name:        "PROGRESS",
				Description: `Mention 1) per-file progress or 2) total transfer progress`,
			}, {
				Name:        "REMOVE",
				Description: `Mention files removed on the sending side`,
			}, {
				Name:        "SKIP",
				Description: `Mention files that are skipped due to options used`,
			}, {
				Name:        "STATS",
				Description: `Mention statistics at end of run (levels 1-3)`,
			}, {
				Name:        "SYMSAFE",
				Description: `Mention symlinks that are unsafe`,
			}, {
				Name:        "ALL",
				Description: `Set all --info options (e.g. all4)`,
			}, {
				Name:        "NONE",
				Description: `Silence all --info options (same as all0)`,
			}, {
				Name:        "HELP",
				Description: `Output this help message`,
			}},
		}, {
			Name:        []string{"--msgs2stderr"},
			Description: `Special output handling for debugging`,
		}, {
			Name:        []string{"--quiet", "-q"},
			Description: `Suppress non-error messages`,
		}, {
			Name:        []string{"--no-motd"},
			Description: `Suppress daemon-mode MOTD (see manpage caveat)`,
		}, {
			Name:        []string{"--checksum", "-c"},
			Description: `Skip based on checksum, not mod-time & size`,
		}, {
			Name:        []string{"-a", "--archive"},
			Description: `Archive mode; equals -rlptgoD (no -H,-A,-X)`,
			ExclusiveOn: []string{"-H", "-A", "-X"},
		}, {
			Name:        []string{"--no-OPTION"},
			Description: `Turn off an implied OPTION (e.g. --no-D)`,
		}, {
			Name:        []string{"-r", "--recursive"},
			Description: `Recurse into directories`,
		}, {
			Name:        []string{"-R", "--relative"},
			Description: `Use relative path names`,
		}, {
			Name:        []string{"--no-implied-dirs"},
			Description: `Don't send implied dirs with --relative`,
		}, {
			Name:        []string{"-b", "--backup"},
			Description: `Make backups (see --suffix & --backup-dir)`,
		}, {
			Name:        []string{"--backup-dir"},
			Description: `Make backups into hierarchy based in DIR`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"--suffix"},
			Description: `Set backup suffix (default ~ w/o --backup-dir)`,
			Args: []model.Arg{{
				Name: "SUFFIX",
			}},
		}, {
			Name:        []string{"-u", "--update"},
			Description: `Skip files that are newer on the receiver`,
		}, {
			Name:        []string{"--inplace"},
			Description: `Update destination files in-place (SEE MAN PAGE)`,
		}, {
			Name:        []string{"--append"},
			Description: `Append data onto shorter files`,
		}, {
			Name:        []string{"--append-verify"},
			Description: `Like --append, but with old data in file checksum`,
		}, {
			Name:        []string{"-d", "--dirs"},
			Description: `Transfer directories without recursing`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"-l", "--links"},
			Description: `Copy symlinks as symlinks`,
		}, {
			Name:        []string{"-L", "--copy-links"},
			Description: `Transform symlink into referent file/dir`,
		}, {
			Name:        []string{"--copy-unsafe-links"},
			Description: `Only "unsafe" symlinks are transformed`,
		}, {
			Name:        []string{"--safe-links"},
			Description: `Ignore symlinks that point outside the source tree`,
		}, {
			Name:        []string{"--munge-links"},
			Description: `Munge symlinks to make them safer (but unusable)`,
		}, {
			Name:        []string{"-k", "--copy-dirlinks"},
			Description: `Transform symlink to a dir into referent dir`,
		}, {
			Name:        []string{"-K", "--keep-dirlinks"},
			Description: `Treat symlinked dir on receiver as dir`,
		}, {
			Name:        []string{"-H", "--hard-links"},
			Description: `Preserve hard links`,
		}, {
			Name:        []string{"-p", "--perms"},
			Description: `Preserve permissions`,
		}, {
			Name:        []string{"-E", "--executability"},
			Description: `Preserve the file's executability`,
		}, {
			Name:        []string{"--chmod"},
			Description: `Affect file and/or directory permissions`,
			Args: []model.Arg{{
				Name: "CHMOD",
			}},
		}, {
			Name:        []string{"-A", "--acls"},
			Description: `Preserve ACLs (implies --perms)`,
		}, {
			Name:        []string{"-X", "--xattrs"},
			Description: `Preserve extended attributes`,
		}, {
			Name:        []string{"-o", "--owner"},
			Description: `Preserve owner (super-user only)`,
		}, {
			Name:        []string{"-g", "--group"},
			Description: `Preserve group`,
		}, {
			Name:        []string{"--devices"},
			Description: `Preserve device files (super-user only)`,
		}, {
			Name:        []string{"--copy-devices"},
			Description: `Copy device contents as regular file`,
		}, {
			Name:        []string{"--specials"},
			Description: `Preserve special files`,
		}, {
			Name:        []string{"-D"},
			Description: `Same as --devices --specials`,
		}, {
			Name:        []string{"-t", "--times"},
			Description: `Preserve modification times`,
		}, {
			Name:        []string{"-O", "--omit-dir-times"},
			Description: `Omit directories from --times`,
			Args: []model.Arg{{
				Templates:  []model.Template{model.TemplateFolders},
				Name:       "DIR",
				IsVariadic: true,
			}},
		}, {
			Name:        []string{"-J", "--omit-link-times"},
			Description: `Omit symlinks from --times`,
		}, {
			Name:        []string{"--super"},
			Description: `Receiver attempts super-user activities`,
		}, {
			Name:        []string{"--fake-super"},
			Description: `Store/recover privileged attrs using xattrs`,
		}, {
			Name:        []string{"-S", "--sparse"},
			Description: `Turn sequences of nulls into sparse blocks`,
		}, {
			Name:        []string{"--preallocate"},
			Description: `Allocate dest files before writing them`,
		}, {
			Name:        []string{"-n", "--dry-run"},
			Description: `Perform a trial run with no changes made`,
		}, {
			Name:        []string{"-W", "--whole-file"},
			Description: `Copy files whole (without delta-xfer algorithm)`,
		}, {
			Name:        []string{"--checksum-choice"},
			Description: `Choose the checksum algorithms`,
			Args: []model.Arg{{
				Name:        "ALGORITHM",
				Suggestions: []model.Suggestion{{Name: []string{`auto`}}, {Name: []string{`md4`}}, {Name: []string{`md5`}}, {Name: []string{`none`}}},
			}},
		}, {
			Name:        []string{"-x", "--one-file-system"},
			Description: `Don't cross filesystem boundaries`,
		}, {
			Name:        []string{"-B", "--block-size"},
			Description: `Force a fixed checksum block-size`,
			Args: []model.Arg{{
				Name: "SIZE",
			}},
		}, {
			Name:        []string{"-e", "--rsh"},
			Description: `Specify the remote shell to use`,
			Args: []model.Arg{{
				Name: "COMMAND",
			}},
		}, {
			Name:        []string{"--rsync-path"},
			Description: `Specify the rsync to run on the remote machine`,
			Args: []model.Arg{{
				Name: "PATH",
			}},
		}, {
			Name:        []string{"--existing"},
			Description: `Skip creating new files on receiver`,
		}, {
			Name:        []string{"--ignore-existing"},
			Description: `Skip updating files that already exist on receiver`,
		}, {
			Name:        []string{"--remove-source-files"},
			Description: `Sender removes synchronized files (non-dirs)`,
		}, {
			Name:        []string{"--delete"},
			Description: `Delete extraneous files from destination dirs`,
		}, {
			Name:        []string{"--delete-before"},
			Description: `Receiver deletes before transfer, not during`,
		}, {
			Name:        []string{"--delete-during", "--del"},
			Description: `Receiver deletes during the transfer`,
		}, {
			Name:        []string{"--delete-delay"},
			Description: `Find deletions during, delete after`,
		}, {
			Name:        []string{"--delete-after"},
			Description: `Receiver deletes after transfer, not during`,
		}, {
			Name:        []string{"--delete-excluded"},
			Description: `Also delete excluded files from destination dirs`,
		}, {
			Name:        []string{"--ignore-missing-args"},
			Description: `Ignore missing source args without error`,
		}, {
			Name:        []string{"--delete-missing-args"},
			Description: `Delete missing source args from destination`,
		}, {
			Name:        []string{"--ignore-errors"},
			Description: `Delete even if there are I/O errors`,
		}, {
			Name:        []string{"--force"},
			Description: `Force deletion of directories even if not empty`,
		}, {
			Name:        []string{"--max-delete"},
			Description: `Don't delete more than NUM files`,
			Args: []model.Arg{{
				Name: "NUM",
			}},
		}, {
			Name:        []string{"--max-size"},
			Description: `Don't transfer any file larger than SIZE`,
			Args: []model.Arg{{
				Name: "SIZE",
			}},
		}, {
			Name:        []string{"--min-size"},
			Description: `Don't transfer any file smaller than SIZE`,
			Args: []model.Arg{{
				Name: "SIZE",
			}},
		}, {
			Name:        []string{"--partial"},
			Description: `Keep partially transferred files`,
		}, {
			Name:        []string{"--partial-dir=DIR"},
			Description: `Put a partially transferred file into DIR`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"--delay-updates"},
			Description: `Put all updated files into place at transfer's end`,
		}, {
			Name:        []string{"-m", "--prune-empty-dirs"},
			Description: `Prune empty directory chains from the file-list`,
		}, {
			Name:        []string{"--numeric-ids"},
			Description: `Don't map uid/gid values by user/group name`,
		}, {
			Name:        []string{"--usermap"},
			Description: `Custom username mapping`,
			Args: []model.Arg{{
				Name: "STRING",
			}},
		}, {
			Name:        []string{"--groupmap"},
			Description: `Custom groupname mapping`,
			Args: []model.Arg{{
				Name: "STRING",
			}},
		}, {
			Name:        []string{"--chown=USER:GROUP"},
			Description: `Simple username/groupname mapping`,
			Args: []model.Arg{{
				Name: "USER:GROUP",
			}},
		}, {
			Name:        []string{"--timeout"},
			Description: `Set I/O timeout in seconds`,
			Args: []model.Arg{{
				Name: "SECONDS",
			}},
		}, {
			Name:        []string{"--contimeout"},
			Description: `Set daemon connection timeout in seconds`,
			Args: []model.Arg{{
				Name: "SECONDS",
			}},
		}, {
			Name:        []string{"-I", "--ignore-times"},
			Description: `Don't skip files that match in size and mod-time`,
		}, {
			Name:        []string{"-M"},
			Description: `Send OPTION to the remote side only`,
			Args: []model.Arg{{
				Name: "OPTION",
			}},
		}, {
			Name:        []string{"--remote-option"},
			Description: `Send OPTION to the remote side only`,
			Args: []model.Arg{{
				Name: "OPTION",
			}},
		}, {
			Name:        []string{"--size-only"},
			Description: `Skip files that match in size`,
		}, {
			Name:        []string{"-@"},
			Description: `Set the accuracy for mod-time comparisons`,
			Args: []model.Arg{{
				Name: "NUM",
			}},
		}, {
			Name:        []string{"--modify-window"},
			Description: `Set the accuracy for mod-time comparisons`,
			Args: []model.Arg{{
				Name: "NUM",
			}},
		}, {
			Name:        []string{"-T"},
			Description: `Create temporary files in directory DIR`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"--temp-dir"},
			Description: `Create temporary files in directory DIR`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"-y", "--fuzzy"},
			Description: `Find similar file for basis if no dest file`,
		}, {
			Name:        []string{"--compare-dest"},
			Description: `Also compare destination files relative to DIR`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"--copy-dest"},
			Description: `Also compare destination files relative to DIR and include copies of unchanged files`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"--link-dest"},
			Description: `Hardlink to files in DIR when unchanged`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFolders},
				Name:      "DIR",
			}},
		}, {
			Name:        []string{"-z", "--compress"},
			Description: `Compress file data during the transfer`,
		}, {
			Name:        []string{"--compress-level"},
			Description: `Explicitly set compression level`,
			Args: []model.Arg{{
				Name:        "NUM",
				Suggestions: []model.Suggestion{{Name: []string{`0`}}, {Name: []string{`1`}}, {Name: []string{`2`}}, {Name: []string{`3`}}, {Name: []string{`4`}}, {Name: []string{`5`}}, {Name: []string{`6`}}, {Name: []string{`7`}}, {Name: []string{`8`}}, {Name: []string{`9`}}},
			}},
		}, {
			Name:        []string{"--skip-compress"},
			Description: `Skip compressing files with a suffix in LIST`,
			Args: []model.Arg{{
				Name: "LIST",
			}},
		}, {
			Name:        []string{"-C", "--cvs-exclude"},
			Description: `Auto-ignore files the same way CVS does`,
		}, {
			Name:        []string{"-f"},
			Description: `Add a file-filtering RULE`,
			Args: []model.Arg{{
				Name: "RULE",
			}},
		}, {
			Name:        []string{"--filter"},
			Description: `Add a file-filtering RULE`,
			Args: []model.Arg{{
				Name: "RULE",
			}},
		}, {
			Name:        []string{"-F"},
			Description: `Same as --filter='dir-merge /.rsync-filter'`,
			Args: []model.Arg{{
				Templates:  []model.Template{model.TemplateFolders},
				Name:       "DIR",
				IsVariadic: true,
			}},
		}, {
			Name:        []string{"--exclude"},
			Description: `Exclude files matching PATTERN`,
			Args: []model.Arg{{
				Name: "PATTERN",
			}},
		}, {
			Name:        []string{"--exclude-from"},
			Description: `Read exclude patterns from FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--include"},
			Description: `Don't exclude files matching PATTERN`,
			Args: []model.Arg{{
				Name: "PATTERN",
			}},
		}, {
			Name:        []string{"--include-from"},
			Description: `Read include patterns from FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--files-from"},
			Description: `Read list of source-file names from FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"-0", "--from0"},
			Description: `All *-from/filter files are delimited by 0s`,
		}, {
			Name:        []string{"-s", "--protect-args"},
			Description: `No space-splitting; only wildcard special-chars`,
		}, {
			Name:        []string{"--address"},
			Description: `Bind address for outgoing socket to daemon`,
			Args: []model.Arg{{
				Name: "ADDRESS",
			}},
		}, {
			Name:        []string{"--port"},
			Description: `Specify double-colon alternate port number`,
			Args: []model.Arg{{
				Name: "PORT",
			}},
		}, {
			Name:        []string{"--sockopts"},
			Description: `Specify custom TCP options`,
			Args: []model.Arg{{
				Name: "OPTIONS",
			}},
		}, {
			Name:        []string{"--blocking-io"},
			Description: `Use blocking I/O for the remote shell`,
		}, {
			Name:        []string{"--stats"},
			Description: `Give some file-transfer stats`,
		}, {
			Name:        []string{"-8", "--8-bit-output"},
			Description: `Leave high-bit chars unescaped in output`,
		}, {
			Name:        []string{"-h", "--human-readable"},
			Description: `Output numbers in a human-readable format`,
		}, {
			Name:        []string{"--progress"},
			Description: `Show progress during transfer`,
		}, {
			Name:        []string{"-P"},
			Description: `Same as --partial --progress`,
		}, {
			Name:        []string{"-i", "--itemize-changes"},
			Description: `Output a change-summary for all updates`,
		}, {
			Name:        []string{"--out-format"},
			Description: `Output updates using the specified FORMAT`,
			Args: []model.Arg{{
				Name: "FORMAT",
			}},
		}, {
			Name:        []string{"--log-file"},
			Description: `Log what we're doing to the specified FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--log-file-format"},
			Description: `Log updates using the specified FMT`,
			Args: []model.Arg{{
				Name: "FMT",
			}},
		}, {
			Name:        []string{"--password-file"},
			Description: `Read daemon-access password from FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--list-only"},
			Description: `List the files instead of copying them`,
		}, {
			Name:        []string{"--bwlimit"},
			Description: `Limit socket I/O bandwidth`,
			Args: []model.Arg{{
				Name: "RATE",
			}},
		}, {
			Name:        []string{"--stop-at"},
			Description: `Stop rsync at year-month-dayThour:minute`,
			Args: []model.Arg{{
				Name: "y-m-dTh:m",
			}},
		}, {
			Name:        []string{"--time-limit"},
			Description: `Stop rsync after MINS minutes have elapsed`,
			Args: []model.Arg{{
				Name: "MINS",
			}},
		}, {
			Name:        []string{"--outbuf"},
			Description: `Set output buffering to None, Line, or Block`,
			Args: []model.Arg{{
				Name:        "BUFFER",
				Suggestions: []model.Suggestion{{Name: []string{`N`}}, {Name: []string{`L`}}, {Name: []string{`B`}}},
			}},
		}, {
			Name:        []string{"--write-batch"},
			Description: `Write a batched update to FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--only-write-batch"},
			Description: `Like --write-batch but w/o updating destination`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--read-batch"},
			Description: `Read a batched update from FILE`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "FILE",
			}},
		}, {
			Name:        []string{"--protocol"},
			Description: `Force an older protocol version to be used`,
			Args: []model.Arg{{
				Name: "NUM",
			}},
		}, {
			Name:        []string{"--iconv"},
			Description: `Request charset conversion of filenames`,
			Args: []model.Arg{{
				Name: "CONVERT_SPEC",
			}},
		}, {
			Name:        []string{"--checksum-seed"},
			Description: `Set block/file checksum seed (advanced)`,
			Args: []model.Arg{{
				Name: "NUM",
			}},
		}, {
			Name:        []string{"--noatime"},
			Description: `Do not alter atime when opening source files`,
		}, {
			Name:        []string{"-4", "--ipv4"},
			Description: `Prefer IPv4`,
		}, {
			Name:        []string{"-6", "--ipv6"},
			Description: `Prefer IPv6`,
		}, {
			Name:        []string{"--version"},
			Description: `Print version number`,
		}, {
			Name:        []string{"-h", "--help"},
			Description: `Show help for rsync (-h is --help only if used alone)`,
		}},
	}
}
