// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["simctl"] = model.Subcommand{
		Name:        []string{"simctl"},
		Description: ``,
		Subcommands: []model.Subcommand{{
			Name:        []string{"addmedia"},
			Description: `Add photos, live photos, videos, or contacts to the library of a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name:       "path",
				IsVariadic: true,
			}},
		}, {
			Name:        []string{"boot"},
			Description: `Boot a device or device pair`,
			Args: []model.Arg{{
				Name: "device",
			}},
			Options: []model.Option{{
				Name:        []string{"--arch"},
				Description: `Specify the architecture to use when booting the simulator (eg: 'arm64' or 'x86_64')`,
			}, {
				Name:        []string{"--disabledJob"},
				Description: `Disables the given launchd job. Multiple jobs can be disabled by passing multiple flags`,
			}, {
				Name:        []string{"--enabledJob"},
				Description: `Enables the given launchd job when it would normally be disabled. Multiple jobs can be enabled by passing multiple flags`,
			}},
		}, {
			Name:        []string{"clone"},
			Description: `Clone an existing device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "new name",
			}, {
				Name:       "destination device set",
				IsVariadic: true,
			}},
		}, {
			Name:        []string{"create"},
			Description: `Create a new device`,
			Args: []model.Arg{{
				Name: "name",
			}, {
				Name:        "device type id",
				Description: `A valid available device type. Find these by running 'xcrun simctl list devicetypes'. Examples: ('iPhone X', 'com.apple.CoreSimulator.SimDeviceType.iPhone-X')`,
			}, {
				Name:        "runtime id",
				Description: `A valid and available runtime. Find these by running 'xcrun simctl list runtimes'. If no runtime is specified the newest runtime compatible with the device type is chosen. Examples: ('watchOS3', 'watchOS3.2', 'watchOS 3.2', 'com.apple.CoreSimulator.SimRuntime.watchOS-3-2', '/Volumes/path/to/Runtimes/watchOS 3.2.simruntime')`,
				IsVariadic:  true,
			}},
		}, {
			Name:        []string{"delete"},
			Description: `Delete specified devices, unavailable devices, or all devices`,
			Args: []model.Arg{{
				Name:       "device",
				IsVariadic: true,
			}, {
				Name:        "unavailable",
				Description: `Specifying unavailable will delete devices that are not supported by the current Xcode SDK`,
			}, {
				Name: "all",
			}},
		}, {
			Name:        []string{"diagnose"},
			Description: `Collect diagnostic information and logs`,
			Options: []model.Option{{
				Name:        []string{"-b"},
				Description: `Do NOT show the resulting archive in a Finder window upon completion`,
			}, {
				Name:        []string{"-X"},
				Description: `Run all diagnostics with no timeout. It ignores the --timeout value if it is specified`,
				ExclusiveOn: []string{"timeout"},
			}, {
				Name:        []string{"--timeout"},
				Description: `Specify a duration (in seconds) to wait for the log collection before timeout`,
			}, {
				Name:        []string{"--output"},
				Description: `Specify the output directory. If not provided the temporary directory is used`,
			}, {
				Name:        []string{"--no-archive"},
				Description: `Do not create an archive, leave the collected files uncompressed`,
			}, {
				Name:        []string{"--all-logs"},
				Description: `Include all device logs, even for non-booted devices`,
			}, {
				Name:        []string{"--data-containers"},
				Description: `Include booted device(s) data directory. Warning: May include private information, app data containers, and increases the size of the archive! Default is NOT to collect the data container`,
			}, {
				Name:        []string{"--udid"},
				Description: `Collect diagnostics only from the specified device. This option may be specified more than once to consider multiple devices. The --all-logs option causes all --udid options to be ignored`,
			}},
		}, {
			Name:        []string{"erase"},
			Description: `Erase a device's contents and settings`,
			Args: []model.Arg{{
				Name:       "device",
				IsVariadic: true,
			}, {
				Name:        "all",
				Description: `Specifying all will erase all existing devices`,
			}},
		}, {
			Name:        []string{"get_app_container"},
			Description: `Print the path of the installed app's container`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "app bundle identifier",
			}, {
				Name: "container",
				Description: `Optionally specify the container. Defaults to app.
app                 The .app bundle
data                The application's data container
groups              The App Group containers
<group identifier>  A specific App Group container`,
				Suggestions: []model.Suggestion{{
					Name:        []string{`app`},
					Description: `The .app bundle`,
				}, {
					Name:        []string{`data`},
					Description: `The application's data container`,
				}, {
					Name:        []string{`groups`},
					Description: `The App Group containers`,
				}, {
					Name:        []string{`<group identifier>`},
					Description: `A specific App Group container`,
				}},
				IsOptional: true,
			}},
		}, {
			Name:        []string{"getenv"},
			Description: `Print an environment variable from a running device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "variable name",
			}},
		}, {
			Name:        []string{"help"},
			Description: `Prints the usage for a given subcommand`,
		}, {
			Name:        []string{"icloud_sync"},
			Description: `Trigger iCloud sync on a device`,
			Args: []model.Arg{{
				Name: "device",
			}},
		}, {
			Name:        []string{"install"},
			Description: `Install an app on a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "path",
			}},
		}, {
			Name:        []string{"install_app_data"},
			Description: `Install an xcappdata package to a device, replacing the current contents of the container`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "path to xcappdata package",
			}},
		}, {
			Name:        []string{"io"},
			Description: `Set up a device IO operation`,
			Args: []model.Arg{{
				Name: "device",
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"enumerate"},
				Description: `Lists all available IO ports and descriptor states`,
				Options: []model.Option{{
					Name:        []string{"--poll"},
					Description: `Poll after enumeration`,
				}},
			}, {
				Name:        []string{"poll"},
				Description: `Polls all available IO ports for events`,
			}, {
				Name:        []string{"recordVideo"},
				Description: `Records the display to a QuickTime movie at the specified file or url`,
				Args: []model.Arg{{
					Name: "file or url",
				}},
				Options: []model.Option{{
					Name:        []string{"--codec"},
					Description: `Specifies the codec type: 'h264' or 'hevc'. Default is 'hevc'`,
				}, {
					Name:        []string{"--display"},
					Description: `iOS: supports 'internal' or 'external'. Default is 'internal'. tvOS: supports only 'external' watchOS: supports only 'internal'`,
				}, {
					Name:        []string{"--mask"},
					Description: `For non-rectangular displays, handle the mask by policy: ignored: The mask is ignored and the unmasked framebuffer is saved. alpha: Not supported, but retained for compatibility; the mask is rendered black. black: The mask is rendered black`,
				}, {
					Name:        []string{"--force"},
					Description: `Force the output file to be written to, even if the file already exists`,
				}},
			}, {
				Name:        []string{"screenshot"},
				Description: `Saves a screenshot as a PNG to the specified file or url(use '-' for stdout)`,
				Args: []model.Arg{{
					Name: "file or url",
				}},
				Options: []model.Option{{
					Name:        []string{"--type"},
					Description: `Can be 'png', 'tiff', 'bmp', 'gif', 'jpeg'. Default is png`,
				}, {
					Name:        []string{"--display"},
					Description: `iOS: supports 'internal' or 'external'. Default is 'internal'. tvOS: supports only 'external' watchOS: supports only 'internal'. You may also specify a port by UUID`,
				}, {
					Name:        []string{"--mask"},
					Description: `For non-rectangular displays, handle the mask by policy: ignored: The mask is ignored and the unmasked framebuffer is saved. alpha: The mask is used as premultiplied alpha. black: The mask is rendered black`,
				}},
			}},
		}, {
			Name:        []string{"keychain"},
			Description: `Manipulate a device's keychain`,
			Subcommands: []model.Subcommand{{
				Name:        []string{"add-root-cert"},
				Description: `Add a certificate to the trusted root store`,
				Args: []model.Arg{{
					Name: "path",
				}},
			}, {
				Name:        []string{"add-cert"},
				Description: `Add a certificate to the keychain`,
				Args: []model.Arg{{
					Name: "path",
				}},
			}, {
				Name:        []string{"reset"},
				Description: `Reset the keychain`,
			}},
		}, {
			Name:        []string{"launch"},
			Description: `Launch an application by identifier on a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "app bundle identifier",
			}, {
				Name:       "argv",
				IsVariadic: true,
			}},
			Options: []model.Option{{
				Name: []string{"-w", "--wait-for-debugger"},
			}, {
				Name:        []string{"--console"},
				Description: `Block and print the application's stdout and stderr to the current terminal. Signals received by simctl are passed through to the application. (Cannot be combined with --stdout or --stderr)`,
				ExclusiveOn: []string{"console-pty", "stdout", "stderr"},
			}, {
				Name:        []string{"--console-pty"},
				Description: `Block and print the application's stdout and stderr to the current terminal via a PTY. Signals received by simctl are passed through to the application. (Cannot be combined with --stdout or --stderr)`,
				ExclusiveOn: []string{"console", "stdout", "stderr"},
			}, {
				Name:        []string{"--stdout"},
				Description: `Redirect the application's standard output to a file`,
				Args: []model.Arg{{
					Name: "path",
				}},
				ExclusiveOn: []string{"console", "console-pty"},
			}, {
				Name:        []string{"--stderr"},
				Description: `Redirect the application's standard error to a file`,
				Args: []model.Arg{{
					Name: "path",
				}},
				ExclusiveOn: []string{"console", "console-pty"},
			}, {
				Name:        []string{"--terminate-running-process"},
				Description: `Terminate any running copy of the application. Note: Log output is often directed to stderr, not stdout`,
			}},
		}, {
			Name:        []string{"list"},
			Description: `List available devices, device types, runtimes, or device pairs`,
			Args: []model.Arg{{
				Name:        "type",
				Suggestions: []model.Suggestion{{Name: []string{`devices`}}, {Name: []string{`deviceTypes`}}, {Name: []string{`runtimes`}}, {Name: []string{`pairs`}}},
			}, {
				Name:        "search term",
				Suggestions: []model.Suggestion{{Name: []string{`available`}}},
			}},
			Options: []model.Option{{
				Name:        []string{"-j", "--json"},
				Description: `Print as JSON`,
			}, {
				Name:        []string{"-e", "--no-escape-slashes"},
				Description: `Encode slashes without escapes in JSON output`,
			}, {
				Name:        []string{"-v"},
				Description: `More verbose output`,
			}},
		}, {
			Name:        []string{"location"},
			Description: `Control a device's simulated location`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "empty",
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"list"},
				Description: `List available simulation scenarios`,
			}, {
				Name:        []string{"clear"},
				Description: `Stop any running scenario and clear any simulated location`,
			}, {
				Name:        []string{"set"},
				Description: `Set the location to a specific latitude and longitude`,
				Args: []model.Arg{{
					Name: "lat,lon",
				}},
			}, {
				Name:        []string{"run"},
				Description: `Run a simulated location scenario (use the list action to get a list of scenarios)`,
				Args: []model.Arg{{
					Name: "scenario",
				}},
			}, {
				Name: []string{"start"},
				Description: `Set the location to a series of waypoints specified as 'lat,lon' pairs, interpolating between them over time.
At least two waypoints are required. Use '-' to read waypoints from stdin, one waypoint per li
Speed specifies how quickly to move between waypoints in meters per second. If not specified 20m/s is us
The system will issue location updates along the path between each pair of waypoints. Use distance or interval to 
control how often those updates are issued. Distance will issue an update every <meters> travelled without regard
for the time between updates. Interval will issue updates at fixed times without regard for how much
the location moves between updates.
If neither are specified an interval of 1.0 seconds is used. If both are specified the system picks on
Example simulating a direct line between San Francisco and New York City, with updates every km:
set --distance=1000 --speed=260 37.629538,-122.395733 40.628083,-73.768254`,
				Args: []model.Arg{{
					Name:       "lat,lon",
					IsVariadic: true,
				}},
				Options: []model.Option{{
					Name: []string{"speed"},
				}, {
					Name: []string{"distance"},
				}, {
					Name: []string{"interval"},
				}},
			}},
		}, {
			Name: []string{"logverbose"},
			Description: `Enable or disable verbose logging for a device.
NOTE: You may need to reboot the affected device before logging changes will be effective`,
			Args: []model.Arg{{
				Name:        "device",
				Description: `The device. If not provided all booted devices are affected`,
			}, {
				Name:        "enable/disable",
				Description: `Enable or Disable verbose logging`,
				Suggestions: []model.Suggestion{{Name: []string{`enable`}}, {Name: []string{`disable`}}},
			}},
		}, {
			Name:        []string{"openurl"},
			Description: `Open a URL in a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "URL",
			}},
		}, {
			Name:        []string{"pair"},
			Description: `Create a new watch and phone pair`,
			Args: []model.Arg{{
				Name: "watch device",
			}, {
				Name: "phone device",
			}},
		}, {
			Name:        []string{"pair_activate"},
			Description: `Set a given pair as active`,
			Args: []model.Arg{{
				Name: "pair",
			}},
		}, {
			Name:        []string{"pbcopy"},
			Description: `Copy standard input onto the device pasteboard`,
			Args: []model.Arg{{
				Name: "device of 'host'",
			}},
			Options: []model.Option{{
				Name: []string{"-v"},
			}},
		}, {
			Name:        []string{"pbpaste"},
			Description: `Print the contents of the device's pasteboard to standard output`,
			Args: []model.Arg{{
				Name: "device of 'host'",
			}},
			Options: []model.Option{{
				Name: []string{"-v"},
			}},
		}, {
			Name:        []string{"pbsync"},
			Description: `Sync the pasteboard content from one pasteboard to another`,
			Args: []model.Arg{{
				Name: "source device or 'host'",
			}, {
				Name: "destination device or 'host'",
			}},
			Options: []model.Option{{
				Name:        []string{"-p"},
				Description: `Causes simctl to use promise data for secondary types.  simctl will continue to run to provide that promise data until something else replaces it on the pasteboard`,
			}, {
				Name: []string{"-v"},
			}},
		}, {
			Name:        []string{"privacy"},
			Description: `Grant, revoke, or reset privacy and permissions`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name:        "action",
				Description: ``,
				Suggestions: []model.Suggestion{{Name: []string{`grant`}}, {Name: []string{`revoke`}}, {Name: []string{`reset`}}},
			}, {
				Name:        "service",
				Description: ``,
				Suggestions: []model.Suggestion{{Name: []string{`all`}}, {Name: []string{`calendar`}}, {Name: []string{`contacts-limited`}}, {Name: []string{`contacts`}}, {Name: []string{`location`}}, {Name: []string{`location-always`}}, {Name: []string{`photos-add`}}, {Name: []string{`photos`}}, {Name: []string{`media-library`}}, {Name: []string{`microphone`}}, {Name: []string{`motion`}}, {Name: []string{`reminders`}}, {Name: []string{`siri`}}},
			}, {
				Name:        "bundle identifier",
				Description: `The bundle identifier of the target application`,
			}},
		}, {
			Name:        []string{"push"},
			Description: `Send a simulated push notification`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name:        "bundle identifier",
				Description: `The bundle identifier of the target application If the payload file contains a 'Simulator Target Bundle' top-level key this parameter may be omitted. If both are provided this argument will override the value from the payload`,
			}, {
				Name: "json file",
				Description: `Path to a JSON payload or '-' to read from stdin. The payload must:
- Contain an object at the top level.
- Contain an 'aps' key with valid Apple Push Notification values.
- Be 4096 bytes or less`,
				Suggestions: []model.Suggestion{{Name: []string{`-`}}},
			}},
		}, {
			Name:        []string{"rename"},
			Description: `Rename a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "name",
			}},
		}, {
			Name:        []string{"runtime"},
			Description: `Perform operations on runtimes`,
			Subcommands: []model.Subcommand{{
				Name:        []string{"add"},
				Description: `Add a runtime disk image to the secure storage area. The image will be staged, verified, and mounted. When possible the image file will be cloned so no additional disk space will be used. If stdout is a terminal and a copy is required then progress will be reported`,
				Args: []model.Arg{{
					Name: "path",
				}},
				Options: []model.Option{{
					Name:        []string{"-m", "--move"},
					Description: `Remove the original file if the image is added successfully. If the image cannot be staged or the add fails the original is not removed`,
				}, {
					Name:        []string{"-a", "--async"},
					Description: `Print the UUID of the new image then exit, do not wait on the results of the add operation`,
				}},
			}, {
				Name:        []string{"delete"},
				Description: `Delete a simulator runtime from the secure storage area. If runtime is a disk image any booted simulators are shutdown and the disk is unmounted first. Use the alias 'all' to delete all images`,
				Args: []model.Arg{{
					Name: "identifier",
				}},
				Options: []model.Option{{
					Name:        []string{"-d", "--notUsedSinceDays"},
					Description: `Delete images not used within the past <days> days`,
				}, {
					Name:        []string{"-n", "--dry-run"},
					Description: `Print what images would be deleted without actually deleting anything`,
					ExclusiveOn: []string{"identifier"},
				}},
			}, {
				Name:        []string{"verify"},
				Description: `Re-verify the signature of a given runtime`,
				Args: []model.Arg{{
					Name: "identifier",
				}},
			}, {
				Name:        []string{"list"},
				Description: ``,
				Options: []model.Option{{
					Name:        []string{"-v"},
					Description: `Print more verbose output`,
				}, {
					Name:        []string{"-j", "--json"},
					Description: `Print as JSON`,
				}},
			}, {
				Name:        []string{"match list"},
				Description: `List the SDK build to runtime build mapping rules for the selected Xcode. Preferred means the runtime was either bundled with Xcode, exactly matched your SDK version, or the downloadable index indicated a better match for your SDK Manual overrides using 'match set' have the highest priority`,
				Options: []model.Option{{
					Name:        []string{"-v"},
					Description: `Verbose mode. Includes the full preferred build map, user override map, and known SDK names`,
				}, {
					Name:        []string{"-j", "--json"},
					Description: `Print as JSON`,
				}},
			}, {
				Name: []string{"match set"},
				Description: `Override the SDK to runtime build mapping. This controls which build of a given runtime Xcode will prefer for building and running when using that SDK. This matters most often during Beta releases when there are multiple builds for a given OS version. If --sdkBuild is not specified it is assumed you mean the SDK build for the currently selected Xcode.

Note: Remember this is about build numbers, not semantic versions. When using the iOS 16.0 SDK Xcwill always prefer an iOS 16.0 runtime. Matching policy controls what to do when there are multiiOS 16.0 runtimes availabeg if the iOS 16.0 SDK is 20A245 and the available runtimes are (20A248, 20A252, 20A254) which should Xcode use for building, SwiftUI Previews, and when launching iOS 16.0 Simulators? They are all iOS 16.0 runtimes so a policy must decide which one is selected`,
				Args: []model.Arg{{
					Name: "sdk canonical name",
				}, {
					Name: "runtime build",
				}},
				Options: []model.Option{{
					Name:        []string{"--default"},
					Description: `Clear the override for the given SDK and revert to default behavior`,
					ExclusiveOn: []string{"runtime build"},
				}, {
					Name:        []string{"--sdkBuild"},
					Description: `Explicitly specify the SDK build, eg for an Xcode other than the selected Xcode`,
				}},
			}},
		}, {
			Name:        []string{"shutdown"},
			Description: `Shutdown a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name:        "all",
				Suggestions: []model.Suggestion{{Name: []string{`all`}}},
			}},
		}, {
			Name:        []string{"spawn"},
			Description: `Spawn a process by executing a given executable on a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "path to executable",
			}, {
				Name:       "argv",
				IsVariadic: true,
			}},
			Options: []model.Option{{
				Name: []string{"-w", "--wait-for-debugger"},
			}, {
				Name: []string{"-s", "--standalone"},
			}, {
				Name: []string{"-a", "--arch"},
			}},
		}, {
			Name:        []string{"status_bar"},
			Description: `Set or clear status bar overrides`,
			Args: []model.Arg{{
				Name: "device",
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"list"},
				Description: `List existing overrides`,
			}, {
				Name:        []string{"clear"},
				Description: `Clear all existing status bar overrides`,
			}, {
				Name:        []string{"override"},
				Description: `Set status bar override values, according to these flags. You may specify any combination of these flags (at least one is required)`,
				Options: []model.Option{{
					Name:        []string{"--time"},
					Description: `Set the date or time to a fixed value. If the string is a valid ISO date string it will also set the date on relevant devices`,
				}, {
					Name:        []string{"--dataNetwork"},
					Description: `If specified must be one of 'hide', 'wifi', '3g', '4g', 'lte', 'lte-a', 'lte+', '5g', '5g+', '5g-uwb', or '5g-uc'`,
				}, {
					Name:        []string{"--wifiMode"},
					Description: `If specified must be one of 'searching', 'failed', or 'active'`,
				}, {
					Name:        []string{"--wifiBars"},
					Description: `If specified must be 0-3`,
				}, {
					Name:        []string{"--cellularMode"},
					Description: `If specified must be one of 'notSupported', 'searching', 'failed', or 'active'`,
				}, {
					Name:        []string{"--cellularBars"},
					Description: `If specified must be 0-4`,
				}, {
					Name:        []string{"--operatorName"},
					Description: `Set the cellular operator/carrier name. Use '' for the empty string`,
				}, {
					Name:        []string{"--batteryState"},
					Description: `If specified must be one of 'charging', 'charged', or 'discharging'`,
				}, {
					Name:        []string{"--batteryLevel"},
					Description: `If specified must be 0-100`,
				}},
			}},
		}, {
			Name:        []string{"terminate"},
			Description: `Terminate an application by identifier on a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "app bundle identifier",
			}},
		}, {
			Name:        []string{"ui"},
			Description: `Get or Set UI options`,
			Args: []model.Arg{{
				Name: "device",
			}},
			Subcommands: []model.Subcommand{{
				Name: []string{"appearance"},
				Description: `When invoked without arguments prints the current user interface appearance style:
light
The Light appearance style.
dark
The Dark appearance style.
unsupported
The platform or runtime version do not support appearance styles.
unknown
The current style is unknown or there was an error detecting it`,
			}, {
				Name: []string{"increase_contrast"},
				Description: `When invoked without arguments prints whether the Increase Contrast mode is currently enabled:
enabled
Increase Contrast is enabled.
disabled
Increase Contrast is disabled.
unsupported
The platform or runtime version do not support the Increase Contrast setting.
unknown
The current setting is unknown or there was an error detecting it`,
			}, {
				Name:        []string{"content_size"},
				Description: `When invoked without arguments prints the current preferred content size category, from the following possible values:`,
			}},
		}, {
			Name:        []string{"uninstall"},
			Description: `Uninstall an app from a device`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "app bundle identifier",
			}},
		}, {
			Name:        []string{"unpair"},
			Description: `Unpair a watch and phone pair`,
			Args: []model.Arg{{
				Name: "pair UUID",
			}},
		}, {
			Name:        []string{"upgrade"},
			Description: `Upgrade a device to a newer runtime`,
			Args: []model.Arg{{
				Name: "device",
			}, {
				Name: "runtime id",
			}},
		}},
	}
}
