// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["sl"] = model.Subcommand{
		Name:        []string{"sl"},
		Description: `A highly advanced animation program for curing your bad habit of mistyping`,
		Options: []model.Option{{
			Name:        []string{"-a"},
			Description: `An accident is occurring; people cry for help`,
		}, {
			Name:        []string{"-l"},
			Description: `Little version`,
		}, {
			Name:        []string{"-F"},
			Description: `It flies like the galaxy express 999`,
		}, {
			Name:        []string{"-c"},
			Description: `C51 appears instead of D51`,
		}},
	}
}
