// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["speedtest-cli"] = model.Subcommand{
		Name:        []string{"speedtest-cli"},
		Description: `Command line interface for testing internet bandwidth using speedtest.net`,
		Options: []model.Option{{
			Name:        []string{"--help", "-h"},
			Description: `Show this help message and exit`,
		}, {
			Name:        []string{"--no-download"},
			Description: `Do not perform download test`,
		}, {
			Name:        []string{"--no-upload"},
			Description: `Do not perform upload test`,
		}, {
			Name:        []string{"--single"},
			Description: `Only use a single connection instead of multiple. This simulates a typical file transfer`,
		}, {
			Name:        []string{"--bytes"},
			Description: `Display values in bytes instead of bits. Does not affect the image generated by --share, nor the output from --json or --csv`,
		}, {
			Name:        []string{"--share"},
			Description: `Generate and provide a URL to the speedtest.net share results image, not displayed with --csv`,
		}, {
			Name:        []string{"--simple"},
			Description: `Suppress verbose output, only show basic information`,
		}, {
			Name:        []string{"--csv"},
			Description: `Suppress verbose output, only show basic information in CSV format. Speeds listed in bit/s and not affected by --bytes`,
		}, {
			Name:        []string{"--csv-delimiter"},
			Description: `Single character delimiter to use in CSV ouput. Default ','`,
			Args: []model.Arg{{
				Name: "CSV_DELIMITER",
			}},
		}, {
			Name:        []string{"--csv-header"},
			Description: `Print CSV headers`,
		}, {
			Name:        []string{"--json"},
			Description: `Suppress verbose output, only show basic information in JSON format. Speeds listed in bit/s and not affected by --bytes`,
		}, {
			Name:        []string{"--list"},
			Description: `Display a list of speedtest.net servers sorted by distance`,
		}, {
			Name:        []string{"--server"},
			Description: `Specify a server ID to test against. Can be supplied multiple times`,
			Args: []model.Arg{{
				Name: "SERVER",
			}},
		}, {
			Name:        []string{"--exclude"},
			Description: `Exclude a server from selection. Can be supplied multiple times`,
			Args: []model.Arg{{
				Name: "EXCLUDE",
			}},
		}, {
			Name:        []string{"--mini"},
			Description: `URL for the Speedtest Mini server`,
			Args: []model.Arg{{
				Name: "MINI",
			}},
		}, {
			Name:        []string{"--source"},
			Description: `Source IP address to bind to`,
			Args: []model.Arg{{
				Name: "SOURCE",
			}},
		}, {
			Name:        []string{"--timeout"},
			Description: `HTTP timeout in seconds. Default 10`,
			Args: []model.Arg{{
				Name: "TIMEOUT",
			}},
		}, {
			Name:        []string{"--secure"},
			Description: `Use HTTPS instead of HTTP when communicating with speedtest.net operated servers`,
		}, {
			Name:        []string{"--no-pre-allocate"},
			Description: `Do not pre allocate upload data. Pre allocation is enabled by default to improve upload performance. To support systems with insufficient memory, use this option to avoid a MemoryError`,
		}, {
			Name:        []string{"--version"},
			Description: `Show the version number and exit`,
		}},
	}
}
