// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["then"] = model.Subcommand{
		Name:        []string{"then"},
		Description: `Execute this command if the test returned 0`,
		Args: []model.Arg{{
			IsCommand: true,
		}},
	}
}
