// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["tsx"] = model.Subcommand{
		Name:        []string{"tsx"},
		Description: `Run TypeScript file using tsx`,
		Args: []model.Arg{{
			Name:      "script path",
			Generator: nil, // TODO: port over generator
		}},
		Options: []model.Option{{
			Name:         []string{"--help", "-h"},
			Description:  `Show help for tsx`,
			IsPersistent: true,
		}, {
			Name:         []string{"--no-cache"},
			Description:  `Disable caching`,
			IsPersistent: true,
		}, {
			Name:        []string{"--clear-screen"},
			Description: `Disable clearing the screen on rerun`,
			Args: []model.Arg{{
				Name:      "script path",
				Generator: nil, // TODO: port over generator
			}},
			IsPersistent: true,
		}, {
			Name:        []string{"-v", "--version"},
			Description: `Show version`,
		}, {
			Name:        []string{"--tsconfig"},
			Description: `Custom tsconfig.json path`,
			Args: []model.Arg{{
				Name:      "tsconfig.json path",
				Generator: nil, // TODO: port over generator
			}},
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"watch"},
			Description: `Run the script and watch for changes`,
			Args: []model.Arg{{
				Name:      "script path",
				Generator: nil, // TODO: port over generator
			}},
		}},
	}
}
