// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.

package specs

import (
	"github.com/cpendery/clac/autocomplete/model"
)

func init() {
	Specs["wrangler"] = model.Subcommand{
		Name:        []string{"wrangler"},
		Description: `Wrangler CLI for Cloudflare Workers`,
		Options: []model.Option{{
			Name:        []string{"-h", "--help"},
			Description: `Prints help information`,
		}, {
			Name:        []string{"--verbose"},
			Description: `Toggle verbose output (when applicable)`,
		}, {
			Name:        []string{"-V", "--version"},
			Description: `Prints version information`,
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"generate"},
			Description: `Generate a new worker project`,
			Args: []model.Arg{{
				Name:        "name",
				Description: `The name of your worker! [default: worker]`,
				IsOptional:  true,
			}, {
				Name: "template",
				Description: `A link to a GitHub template! Defaults to 
https://github.com/cloudflare/worker-template`,
				IsOptional: true,
			}},
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name: []string{"-s", "--site"},
				Description: `Initializes a Workers Sites project. Overrides 'type' 
and 'template'`,
				Args: []model.Arg{{
					Name:       "site",
					IsOptional: true,
				}},
			}, {
				Name:        []string{"-t", "--type"},
				Description: `The type of project you want generated`,
				Args: []model.Arg{{
					Name:       "type",
					IsOptional: true,
				}},
			}},
		}, {
			Name:        []string{"kv:namespace"},
			Description: `Interact with your Workers KV Namespaces`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"create"},
				Description: `Create a new namespace`,
				Args: []model.Arg{{
					Name: "namespace",
				}},
			}, {
				Name:        []string{"delete"},
				Description: `Delete namespace`,
			}, {
				Name:        []string{"list"},
				Description: `List all namespaces on your Cloudflare account`,
			}},
		}, {
			Name:        []string{"kv:key"},
			Description: `Individually manage Workers KV key-value`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"delete"},
				Description: `Delete a key and its value from a namespace`,
				Args: []model.Arg{{
					Name:        "key",
					Description: `Key whose value to delete`,
				}},
				Options: []model.Option{{
					Name:        []string{"-b", "--binding"},
					Description: `The binding of the namespace this action applies to`,
					Args: []model.Arg{{
						Name: "binding",
					}},
				}, {
					Name:        []string{"-n", "--namespace-id"},
					Description: `The ID of the namespace this action applies to`,
					Args: []model.Arg{{
						Name: "namespace-id",
					}},
				}},
			}, {
				Name:        []string{"get"},
				Description: `Get a key's value from a namespace`,
				Args: []model.Arg{{
					Name: "key",
				}},
			}, {
				Name:        []string{"help"},
				Description: `Prints this message or the help of the given subcommand(s)`,
			}, {
				Name:        []string{"list"},
				Description: `List all keys in a namespace. Produces JSON output`,
			}, {
				Name:        []string{"put"},
				Description: `Put a key-value pair into a namespace`,
				Args: []model.Arg{{
					Name: "key",
				}},
			}},
		}, {
			Name:        []string{"kv:bulk"},
			Description: `Interact with multiple Workers KV key-value pairs at once`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"delete"},
				Description: `Delete multiple keys and their values from a namespace`,
				Args: []model.Arg{{
					Name: "keys",
				}},
			}, {
				Name:        []string{"help"},
				Description: `Prints this message or the help of the given subcommand(s)`,
			}, {
				Name:        []string{"put"},
				Description: `Upload multiple key-value pairs to a namespace`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "keys",
				}},
			}},
		}, {
			Name:        []string{"route"},
			Description: `List or delete worker routes`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"delete"},
				Description: `Delete a route by ID`,
				Args: []model.Arg{{
					Name: "routeId",
				}},
			}, {
				Name:        []string{"list"},
				Description: `List all routes associated with a zone (outputs json)`,
			}},
		}, {
			Name:        []string{"secret"},
			Description: `Generate a secret that can be referenced in the worker script`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
			Subcommands: []model.Subcommand{{
				Name:        []string{"delete"},
				Description: `Delete a secret variable from a script`,
				Args: []model.Arg{{
					Name: "secret",
				}},
			}, {
				Name:        []string{"list"},
				Description: `List all secrets for a script`,
			}, {
				Name:        []string{"put"},
				Description: `Create or update a secret variable for a script`,
				Args: []model.Arg{{
					Name: "secret",
				}},
			}},
		}, {
			Name:        []string{"init"},
			Description: `Create a wrangler.toml for an existing project`,
			Args: []model.Arg{{
				Name:        "name",
				Description: `The name of your worker! [default: worker]`,
				IsOptional:  true,
			}},
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name: []string{"-s", "--site"},
				Description: `Initializes a Workers Sites project. Overrides 'type' 
and 'template'`,
			}, {
				Name:        []string{"-t", "--type"},
				Description: `The type of project you want generated`,
				Args: []model.Arg{{
					Name:       "type",
					IsOptional: true,
				}},
			}},
		}, {
			Name:        []string{"build"},
			Description: `Build your worker`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
		}, {
			Name:        []string{"preview"},
			Description: `Preview your code temporarily on cloudflareworkers.com`,
			Args: []model.Arg{{
				Name: "method",
				Description: `Type of request to preview your worker with (get, post) 
[default: get]`,
				Suggestions: []model.Suggestion{{Name: []string{`get`}}, {Name: []string{`post`}}},
				IsOptional:  true,
			}, {
				Name:        "body",
				Description: `Body string to post to your preview worker request`,
				IsOptional:  true,
			}},
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name:        []string{"--headless"},
				Description: `Don't open the browser on preview`,
			}, {
				Name: []string{"--watch"},
				Description: `Watch your project for changes and update the preview 
automagically`,
			}, {
				Name: []string{"-u", "--url"},
				Description: `URL to open in the worker preview 
[default: https://example.com]`,
			}},
		}, {
			Name:        []string{"dev"},
			Description: `Start a local server for developing your worker`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name: []string{"-h", "--host"},
				Description: `Host to forward requests to, defaults to the zone of 
project or to tutorial.cloudflareworkers.com if unauthenticated`,
				Args: []model.Arg{{
					Name: "hostname",
				}},
			}, {
				Name:        []string{"-i", "--ip"},
				Description: `IP to listen on. Defaults to 127.0.0.1`,
				Args: []model.Arg{{
					Name: "ip_address",
				}},
			}, {
				Name:        []string{"-p", "--port"},
				Description: `Port to listen on. Defaults to 8787`,
				Args: []model.Arg{{
					Name: "port",
				}},
			}},
		}, {
			Name:        []string{"publish"},
			Description: `Publish your worker to the orange cloud`,
			Args: []model.Arg{{
				Name:        "output",
				Description: `[possible values: json]`,
				Suggestions: []model.Suggestion{{Name: []string{`json`}}},
				IsOptional:  true,
			}},
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name:        []string{"--delete-class"},
				Description: `Delete all durable objects associated with a class in your script`,
				Args: []model.Arg{{
					Name: "delete-class",
				}},
			}, {
				Name:        []string{"--new-class"},
				Description: `Allow durable objects to be created from a class in your script`,
				Args: []model.Arg{{
					Name: "new-class",
				}},
			}, {
				Name:        []string{"--rename-class"},
				Description: `Rename a durable object class in your script`,
				Args: []model.Arg{{
					Name: "rename-class new-name",
				}},
			}, {
				Name:        []string{"--transfer-class"},
				Description: `Transfer all durable objects associated with a class in another script to a class in this script`,
				Args: []model.Arg{{
					Name: "transfer-class",
				}},
			}},
		}, {
			Name:        []string{"config"},
			Description: `Authenticate Wrangler with a Cloudflare API Token or Global API Key`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name:        []string{"--api-key"},
				Description: `Use an email and global API key for authentication. This is not recommended; use API tokens (the default) if possible`,
			}, {
				Name:        []string{"--no-verify"},
				Description: `Do not verify provided credentials before writing out Wrangler config file`,
			}},
		}, {
			Name:        []string{"subdomain"},
			Description: `Configure your workers.dev subdomain`,
			Args: []model.Arg{{
				Name:        "name",
				Description: `The subdomain on workers.dev you'd like to reserve`,
			}},
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
		}, {
			Name:        []string{"whoami"},
			Description: `Retrieve your user info and test your auth config`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
		}, {
			Name:        []string{"tail"},
			Description: `Aggregate logs from production worker`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name:        []string{"-f", "--format"},
				Description: `Specify an output format [default: json]  [possible values: json, pretty]`,
				Args: []model.Arg{{
					Name:        "format",
					Suggestions: []model.Suggestion{{Name: []string{`json`}}, {Name: []string{`pretty`}}},
				}},
			}, {
				Name:        []string{"--metrics"},
				Description: `Provides endpoint for cloudflared metrics. Used to retrieve tunnel url`,
				Args: []model.Arg{{
					Name: "metrics-port",
				}},
			}, {
				Name:        []string{"-p", "--port"},
				Description: `Port to accept tail log requests`,
				Args: []model.Arg{{
					Name: "port",
				}},
			}},
		}, {
			Name:        []string{"login"},
			Description: `Authenticate Wrangler with your Cloudflare username and password`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}},
		}, {
			Name:        []string{"report"},
			Description: `Report an error caught by Wrangler to Cloudflare`,
			Options: []model.Option{{
				Name:        []string{"-c", "--config"},
				Description: `Path to configuration file [default: wrangler.toml]`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "wrangler.toml",
				}},
			}, {
				Name:        []string{"-e", "--env"},
				Description: `Environment to perform a command on`,
				Args: []model.Arg{{
					Name: "environment",
				}},
			}, {
				Name:        []string{"-h", "--help"},
				Description: `Prints help information`,
			}, {
				Name:        []string{"--verbose"},
				Description: `Toggle verbose output (when applicable)`,
			}, {
				Name:        []string{"log"},
				Description: `Specifies a log to report (e.g. --log=1619728882567.log)`,
				Args: []model.Arg{{
					Templates: []model.Template{model.TemplateFilepaths},
					Name:      "logfile",
				}},
			}},
		}, {
			Name:        []string{"help"},
			Description: `Prints this message or the help of the given subcommand(s)`,
			Args: []model.Arg{{
				Name: "command",
			}},
		}},
	}
}
