// Code generated by autocomplete/extract/extract.ts. DO NOT EDIT.
//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package specs

import (
	"github.com/microsoft/clac/autocomplete/model"
)

func init() {
	Specs["xdg-mime"] = model.Subcommand{
		Name:        []string{"xdg-mime"},
		Description: `Command line tool for querying information about file type handling and adding descriptions for new file types`,
		Options: []model.Option{{
			Name:        []string{"--help"},
			Description: `Show command synopsis`,
		}, {
			Name:        []string{"--manual"},
			Description: `Show manual page`,
		}, {
			Name:        []string{"--version"},
			Description: `Show the xdg-utils version information`,
		}},
		Subcommands: []model.Subcommand{{
			Name:        []string{"query"},
			Description: `Returns information related to file types`,
			Args: []model.Arg{{
				Templates:  []model.Template{model.TemplateFilepaths},
				Name:       "filetype | default",
				IsVariadic: true,
			}},
		}, {
			Name:        []string{"default"},
			Description: `Ask the desktop environment to make application the default application for opening files of type mimetype`,
			Args: []model.Arg{{
				Name: "application",
			}, {
				Name:       "mimetype(s)",
				IsVariadic: true,
			}},
		}, {
			Name:        []string{"install"},
			Description: `Adds the file type descriptions provided in mimetypes-file to the desktop environment`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "mimetypes-file",
			}},
			Options: []model.Option{{
				Name: []string{"--mode"},
				Args: []model.Arg{{
					Name:        "mode",
					Suggestions: []model.Suggestion{{Name: []string{`user`}}, {Name: []string{`system`}}},
				}},
			}, {
				Name:        []string{"--novendor"},
				Description: `Disables xdg-mime checks that the mimetypes-file to be installed has a proper vendor prefix`,
			}},
		}, {
			Name:        []string{"uninstall"},
			Description: `Removes the file type descriptions provided in mimetypes-file and previously added with xdg-mime install from the desktop environment`,
			Args: []model.Arg{{
				Templates: []model.Template{model.TemplateFilepaths},
				Name:      "mimetypes-file",
			}},
			Options: []model.Option{{
				Name: []string{"--mode"},
				Args: []model.Arg{{
					Name:        "mode",
					Suggestions: []model.Suggestion{{Name: []string{`user`}}, {Name: []string{`system`}}},
				}},
			}},
		}},
	}
}
